// GENERATED by scripts/gen-types.ts from supabase/migrations — do not edit.
/* eslint-disable */
export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export type AppRole = "super_admin" | "admin" | "sales" | "designer" | "production" | "marketing" | "customer";
export type BillboardStatus = "available" | "reserved" | "unavailable" | "maintenance";
export type BookingStatus = "requested" | "in_review" | "confirmed" | "declined" | "cancelled" | "completed";
export type ConsultationStatus = "requested" | "approved" | "declined" | "alternative_suggested" | "completed" | "converted";
export type DeliveryStatus = "pending" | "scheduled" | "in_transit" | "delivered" | "installed" | "failed";
export type DesignStatus = "draft" | "saved" | "submitted" | "approved" | "archived";
export type LeadSource = "quote" | "consultation" | "mockup" | "billboard" | "project_builder" | "contact" | "preorder" | "campaign" | "whatsapp" | "social" | "qr" | "manual";
export type LeadStatus = "new" | "contacted" | "qualified" | "quote" | "negotiation" | "won" | "lost";
export type OrderStatus = "quote" | "approved" | "artwork_review" | "production" | "quality_control" | "ready" | "delivery" | "completed" | "cancelled";
export type PaymentStatus = "unpaid" | "deposit" | "paid" | "refunded";
export type PreflightVerdict = "ready" | "attention" | "blocked";
export type PricingMode = "fixed" | "estimated" | "quote";
export type PriorityLevel = "low" | "normal" | "high" | "urgent";
export type ProductionStatus = "queued" | "in_progress" | "blocked" | "qc" | "done";
export type ProjectStage = "discovery" | "design" | "artwork" | "approval" | "production" | "quality_control" | "delivery" | "completion";
export type PublishStatus = "draft" | "scheduled" | "published" | "archived";
export type QcResult = "pass" | "fail" | "needs_review";
export type QuoteStatus = "draft" | "submitted" | "in_review" | "sent" | "accepted" | "declined" | "expired";

export type AbandonedActivitiesRow = {
  id: string;
  session_id: string;
  user_id: string | null;
  flow: string;
  stage: string;
  product_slug: string | null;
  ref: string | null;
  contact_email: string | null;
  recovery_consent: boolean;
  resume_href: string;
  last_seen: string;
  converted: boolean;
  contacted_at: string | null;
};
export type AbandonedActivitiesInsert = {
  id?: string;
  session_id: string;
  user_id?: string | null;
  flow: string;
  stage: string;
  product_slug?: string | null;
  ref?: string | null;
  contact_email?: string | null;
  recovery_consent?: boolean;
  resume_href?: string;
  last_seen?: string;
  converted?: boolean;
  contacted_at?: string | null;
};

export type AiUsageRow = {
  id: number;
  user_id: string;
  task: string;
  at: string;
};
export type AiUsageInsert = {
  id?: number;
  user_id: string;
  task?: string;
  at?: string;
};

export type AnalyticsEventsRow = {
  id: number;
  at: string;
  session_id: string;
  user_id: string | null;
  name: string;
  path: string;
  product_slug: string | null;
  ref: string | null;
  step: string | null;
  source: string | null;
  value_lak: number | null;
};
export type AnalyticsEventsInsert = {
  id?: number;
  at?: string;
  session_id: string;
  user_id?: string | null;
  name: string;
  path?: string;
  product_slug?: string | null;
  ref?: string | null;
  step?: string | null;
  source?: string | null;
  value_lak?: number | null;
};

export type ArtworkPreflightsRow = {
  id: string;
  design_id: string;
  design_version: number;
  verdict: PreflightVerdict;
  checks: Json;
  reviewed_by: string | null;
  review_verdict: PreflightVerdict | null;
  review_note: string;
  created_at: string;
};
export type ArtworkPreflightsInsert = {
  id?: string;
  design_id: string;
  design_version: number;
  verdict: PreflightVerdict;
  checks: Json;
  reviewed_by?: string | null;
  review_verdict?: PreflightVerdict | null;
  review_note?: string;
  created_at?: string;
};

export type AttachmentsRow = {
  id: string;
  entity: string;
  entity_id: string;
  owner_id: string | null;
  path: string;
  file_name: string;
  mime: string;
  bytes: number;
  internal: boolean;
  created_at: string;
};
export type AttachmentsInsert = {
  id?: string;
  entity: string;
  entity_id: string;
  owner_id?: string | null;
  path: string;
  file_name: string;
  mime: string;
  bytes: number;
  internal?: boolean;
  created_at?: string;
};

export type AuditLogRow = {
  id: number;
  at: string;
  actor: string | null;
  actor_role: AppRole | null;
  action: string;
  entity: string;
  entity_id: string | null;
  before: Json | null;
  after: Json | null;
  ip: string | null;
};
export type AuditLogInsert = {
  id?: number;
  at?: string;
  actor?: string | null;
  actor_role?: AppRole | null;
  action: string;
  entity: string;
  entity_id?: string | null;
  before?: Json | null;
  after?: Json | null;
  ip?: string | null;
};

export type BillboardAvailabilityRow = {
  id: string;
  billboard_id: string;
  starts_on: string;
  ends_on: string;
  kind: string;
  booking_id: string | null;
  note: string;
};
export type BillboardAvailabilityInsert = {
  id?: string;
  billboard_id: string;
  starts_on: string;
  ends_on: string;
  kind: string;
  booking_id?: string | null;
  note?: string;
};

export type BillboardBookingsRow = {
  id: string;
  ref: string;
  billboard_id: string;
  lead_id: string | null;
  customer_id: string | null;
  contact: Json;
  starts_on: string;
  ends_on: string;
  design_asset_id: string | null;
  needs_design: boolean;
  needs_print_install: boolean;
  notes: string;
  status: BookingStatus;
  quoted_usd: number | null;
  campaign_id: string | null;
  created_at: string;
  updated_at: string;
};
export type BillboardBookingsInsert = {
  id?: string;
  ref: string;
  billboard_id: string;
  lead_id?: string | null;
  customer_id?: string | null;
  contact?: Json;
  starts_on: string;
  ends_on: string;
  design_asset_id?: string | null;
  needs_design?: boolean;
  needs_print_install?: boolean;
  notes?: string;
  status?: BookingStatus;
  quoted_usd?: number | null;
  campaign_id?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type BillboardMediaRow = {
  billboard_id: string;
  media_id: string;
  sort: number;
};
export type BillboardMediaInsert = {
  billboard_id: string;
  media_id: string;
  sort?: number;
};

export type BillboardsRow = {
  id: string;
  code: string;
  name: string;
  province: string;
  district: string;
  address: string;
  lat: number;
  lng: number;
  width_m: number;
  height_m: number;
  orientation: string;
  faces: number;
  facing: string;
  lit: boolean;
  visibility: string;
  traffic: string | null;
  status: BillboardStatus;
  available_from: string | null;
  pricing_mode: PricingMode;
  price_from_usd_month: number | null;
  min_months: number;
  installation: string;
  description: string;
  verified: boolean;
  publish: PublishStatus;
  created_at: string;
  updated_at: string;
};
export type BillboardsInsert = {
  id?: string;
  code: string;
  name: string;
  province: string;
  district?: string;
  address?: string;
  lat: number;
  lng: number;
  width_m: number;
  height_m: number;
  orientation?: string;
  faces?: number;
  facing?: string;
  lit?: boolean;
  visibility?: string;
  traffic?: string | null;
  status?: BillboardStatus;
  available_from?: string | null;
  pricing_mode?: PricingMode;
  price_from_usd_month?: number | null;
  min_months?: number;
  installation?: string;
  description?: string;
  verified?: boolean;
  publish?: PublishStatus;
  created_at?: string;
  updated_at?: string;
};

export type BlogPostsRow = {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  body: string;
  tag: string;
  read_mins: number;
  author_id: string | null;
  cover_media_id: string | null;
  seo: Json;
  status: PublishStatus;
  published_at: string | null;
  publish_at: string | null;
  updated_at: string;
};
export type BlogPostsInsert = {
  id?: string;
  slug: string;
  title: string;
  excerpt?: string;
  body?: string;
  tag?: string;
  read_mins?: number;
  author_id?: string | null;
  cover_media_id?: string | null;
  seo?: Json;
  status?: PublishStatus;
  published_at?: string | null;
  publish_at?: string | null;
  updated_at?: string;
};

export type BrandAssetsRow = {
  id: string;
  owner_id: string;
  kind: string;
  path: string;
  file_name: string;
  mime: string;
  bytes: number;
  width: number | null;
  height: number | null;
  created_at: string;
};
export type BrandAssetsInsert = {
  id?: string;
  owner_id: string;
  kind: string;
  path: string;
  file_name: string;
  mime: string;
  bytes: number;
  width?: number | null;
  height?: number | null;
  created_at?: string;
};

export type BrandProfilesRow = {
  id: string;
  owner_id: string;
  company_id: string | null;
  brand_name: string;
  colours: Json;
  fonts: string[];
  guidelines: string;
  updated_at: string;
};
export type BrandProfilesInsert = {
  id?: string;
  owner_id: string;
  company_id?: string | null;
  brand_name?: string;
  colours?: Json;
  fonts?: string[];
  guidelines?: string;
  updated_at?: string;
};

export type BundleItemsRow = {
  id: string;
  bundle_id: string;
  product_id: string;
  qty: number;
  note: string;
  sort: number;
  updated_at: string;
};
export type BundleItemsInsert = {
  id?: string;
  bundle_id: string;
  product_id: string;
  qty?: number;
  note?: string;
  sort?: number;
  updated_at?: string;
};

export type BundlesRow = {
  id: string;
  slug: string;
  name: string;
  summary: string;
  discount_pct: number;
  featured: boolean;
  status: PublishStatus;
  updated_at: string;
};
export type BundlesInsert = {
  id?: string;
  slug: string;
  name: string;
  summary?: string;
  discount_pct?: number;
  featured?: boolean;
  status?: PublishStatus;
  updated_at?: string;
};

export type CampaignQrCodesRow = {
  id: string;
  code: string;
  campaign_id: string;
  billboard_id: string | null;
  medium: string;
  label: string;
  destination: string;
  active: boolean;
  created_at: string;
};
export type CampaignQrCodesInsert = {
  id?: string;
  code: string;
  campaign_id: string;
  billboard_id?: string | null;
  medium?: string;
  label?: string;
  destination?: string;
  active?: boolean;
  created_at?: string;
};

export type CampaignsRow = {
  id: string;
  slug: string;
  name: string;
  summary: string;
  body: string;
  cta_label: string;
  cta_href: string;
  product_slugs: string[];
  offer: string;
  starts_on: string | null;
  ends_on: string | null;
  hero_media_id: string | null;
  status: PublishStatus;
  created_at: string;
  updated_at: string;
};
export type CampaignsInsert = {
  id?: string;
  slug: string;
  name: string;
  summary?: string;
  body?: string;
  cta_label?: string;
  cta_href?: string;
  product_slugs?: string[];
  offer?: string;
  starts_on?: string | null;
  ends_on?: string | null;
  hero_media_id?: string | null;
  status?: PublishStatus;
  created_at?: string;
  updated_at?: string;
};

export type CategoriesRow = {
  id: string;
  slug: string;
  name: string;
  blurb: string;
  plate: string;
  sort: number;
  status: PublishStatus;
  updated_at: string;
};
export type CategoriesInsert = {
  id?: string;
  slug: string;
  name: string;
  blurb?: string;
  plate?: string;
  sort?: number;
  status?: PublishStatus;
  updated_at?: string;
};

export type CompaniesRow = {
  id: string;
  name: string;
  sector: string;
  address: string;
  tax_id: string;
  notes_internal: string;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};
export type CompaniesInsert = {
  id?: string;
  name: string;
  sector?: string;
  address?: string;
  tax_id?: string;
  notes_internal?: string;
  created_by?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type ConsultationsRow = {
  id: string;
  ref: string;
  lead_id: string | null;
  customer_id: string | null;
  name: string;
  company_name: string;
  email: string;
  phone: string;
  topic: string;
  goal: string;
  duration_mins: number;
  preferred_at: string;
  alternative_at: string | null;
  confirmed_at: string | null;
  channel: string;
  info: string;
  status: ConsultationStatus;
  project_id: string | null;
  created_at: string;
  updated_at: string;
};
export type ConsultationsInsert = {
  id?: string;
  ref: string;
  lead_id?: string | null;
  customer_id?: string | null;
  name: string;
  company_name?: string;
  email: string;
  phone?: string;
  topic: string;
  goal?: string;
  duration_mins: number;
  preferred_at: string;
  alternative_at?: string | null;
  confirmed_at?: string | null;
  channel?: string;
  info?: string;
  status?: ConsultationStatus;
  project_id?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type DeliveriesRow = {
  id: string;
  order_id: string;
  method: string;
  status: DeliveryStatus;
  scheduled_for: string | null;
  address: string;
  carrier: string;
  tracking: string;
  proof_path: string | null;
  note: string;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
};
export type DeliveriesInsert = {
  id?: string;
  order_id: string;
  method?: string;
  status?: DeliveryStatus;
  scheduled_for?: string | null;
  address?: string;
  carrier?: string;
  tracking?: string;
  proof_path?: string | null;
  note?: string;
  completed_at?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type DesignAssetsRow = {
  id: string;
  design_id: string | null;
  owner_id: string;
  path: string;
  file_name: string;
  mime: string;
  bytes: number;
  width: number | null;
  height: number | null;
  created_at: string;
};
export type DesignAssetsInsert = {
  id?: string;
  design_id?: string | null;
  owner_id: string;
  path: string;
  file_name: string;
  mime: string;
  bytes: number;
  width?: number | null;
  height?: number | null;
  created_at?: string;
};

export type DesignTemplatesRow = {
  id: string;
  slug: string;
  name: string;
  category: string;
  garments: string[];
  suggested_colour: string;
  sides: Json;
  featured: boolean;
  sort: number;
  status: PublishStatus;
  updated_at: string;
};
export type DesignTemplatesInsert = {
  id?: string;
  slug: string;
  name: string;
  category: string;
  garments?: string[];
  suggested_colour?: string;
  sides?: Json;
  featured?: boolean;
  sort?: number;
  status?: PublishStatus;
  updated_at?: string;
};

export type DesignVersionsRow = {
  id: string;
  design_id: string;
  version: number;
  colour: string;
  sides: Json;
  note: string;
  created_by: string | null;
  created_at: string;
};
export type DesignVersionsInsert = {
  id?: string;
  design_id: string;
  version: number;
  colour: string;
  sides: Json;
  note?: string;
  created_by?: string | null;
  created_at?: string;
};

export type DesignsRow = {
  id: string;
  ref: string;
  owner_id: string;
  name: string;
  product_slug: string;
  garment: string;
  colour: string;
  size: string | null;
  sides: Json;
  preview_path: string | null;
  status: DesignStatus;
  version: number;
  share_token: string | null;
  template_slug: string | null;
  created_at: string;
  updated_at: string;
};
export type DesignsInsert = {
  id?: string;
  ref: string;
  owner_id: string;
  name?: string;
  product_slug: string;
  garment: string;
  colour?: string;
  size?: string | null;
  sides?: Json;
  preview_path?: string | null;
  status?: DesignStatus;
  version?: number;
  share_token?: string | null;
  template_slug?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type EmailOutboxRow = {
  id: string;
  to_email: string;
  template: string;
  subject: string;
  vars: Json;
  status: string;
  error: string | null;
  created_at: string;
  sent_at: string | null;
};
export type EmailOutboxInsert = {
  id?: string;
  to_email: string;
  template: string;
  subject: string;
  vars?: Json;
  status?: string;
  error?: string | null;
  created_at?: string;
  sent_at?: string | null;
};

export type FaqsRow = {
  id: string;
  topic: string;
  q: string;
  a: string;
  sort: number;
  status: PublishStatus;
  updated_at: string;
};
export type FaqsInsert = {
  id?: string;
  topic?: string;
  q: string;
  a: string;
  sort?: number;
  status?: PublishStatus;
  updated_at?: string;
};

export type FeatureFlagsRow = {
  key: string;
  enabled: boolean;
  description: string;
  updated_at: string;
};
export type FeatureFlagsInsert = {
  key: string;
  enabled?: boolean;
  description?: string;
  updated_at?: string;
};

export type InternalNotesRow = {
  id: string;
  entity: string;
  entity_id: string;
  body: string;
  author: string | null;
  created_at: string;
};
export type InternalNotesInsert = {
  id?: string;
  entity: string;
  entity_id: string;
  body: string;
  author?: string | null;
  created_at?: string;
};

export type LeadActivitiesRow = {
  id: string;
  lead_id: string;
  kind: string;
  body: string;
  meta: Json;
  actor: string | null;
  at: string;
};
export type LeadActivitiesInsert = {
  id?: string;
  lead_id: string;
  kind: string;
  body?: string;
  meta?: Json;
  actor?: string | null;
  at?: string;
};

export type LeadsRow = {
  id: string;
  ref: string;
  customer_id: string | null;
  company_id: string | null;
  name: string;
  company_name: string;
  email: string | null;
  phone: string;
  social_contact: string;
  department: string;
  source: LeadSource;
  source_detail: string;
  product_interest: string[];
  message: string;
  estimated_value_lak: number | null;
  priority: PriorityLevel;
  status: LeadStatus;
  lost_reason: string | null;
  assigned_to: string | null;
  follow_up_on: string | null;
  marketing_consent: boolean;
  created_at: string;
  updated_at: string;
};
export type LeadsInsert = {
  id?: string;
  ref: string;
  customer_id?: string | null;
  company_id?: string | null;
  name: string;
  company_name?: string;
  email?: string | null;
  phone?: string;
  social_contact?: string;
  department?: string;
  source: LeadSource;
  source_detail?: string;
  product_interest?: string[];
  message?: string;
  estimated_value_lak?: number | null;
  priority?: PriorityLevel;
  status?: LeadStatus;
  lost_reason?: string | null;
  assigned_to?: string | null;
  follow_up_on?: string | null;
  marketing_consent?: boolean;
  created_at?: string;
  updated_at?: string;
};

export type MediaRow = {
  id: string;
  bucket: string;
  path: string;
  file_name: string;
  mime: string;
  bytes: number;
  width: number | null;
  height: number | null;
  alt: string;
  category: string;
  tags: string[];
  uploaded_by: string | null;
  created_at: string;
};
export type MediaInsert = {
  id?: string;
  bucket?: string;
  path: string;
  file_name: string;
  mime: string;
  bytes: number;
  width?: number | null;
  height?: number | null;
  alt?: string;
  category?: string;
  tags?: string[];
  uploaded_by?: string | null;
  created_at?: string;
};

export type MessagesRow = {
  id: string;
  entity: string;
  entity_id: string;
  customer_id: string | null;
  sender: string | null;
  from_staff: boolean;
  body: string;
  created_at: string;
};
export type MessagesInsert = {
  id?: string;
  entity: string;
  entity_id: string;
  customer_id?: string | null;
  sender?: string | null;
  from_staff?: boolean;
  body: string;
  created_at?: string;
};

export type NotificationsRow = {
  id: string;
  user_id: string | null;
  audience: string | null;
  kind: string;
  title: string;
  body: string;
  href: string;
  read_at: string | null;
  created_at: string;
};
export type NotificationsInsert = {
  id?: string;
  user_id?: string | null;
  audience?: string | null;
  kind: string;
  title: string;
  body?: string;
  href?: string;
  read_at?: string | null;
  created_at?: string;
};

export type OrderItemsRow = {
  id: string;
  order_id: string;
  quote_item_id: string | null;
  product_id: string | null;
  product_slug: string;
  product_name: string;
  design_id: string | null;
  design_version: number | null;
  qty: number;
  config: Json;
  unit_price_lak: number | null;
  line_total_lak: number | null;
  sort: number;
};
export type OrderItemsInsert = {
  id?: string;
  order_id: string;
  quote_item_id?: string | null;
  product_id?: string | null;
  product_slug: string;
  product_name: string;
  design_id?: string | null;
  design_version?: number | null;
  qty: number;
  config?: Json;
  unit_price_lak?: number | null;
  line_total_lak?: number | null;
  sort?: number;
};

export type OrdersRow = {
  id: string;
  ref: string;
  quote_id: string | null;
  lead_id: string | null;
  project_id: string | null;
  customer_id: string | null;
  contact: Json;
  status: OrderStatus;
  payment_status: PaymentStatus;
  total_lak: number | null;
  due_on: string | null;
  delivery_method: string;
  delivery_address: string;
  customer_confirmed_at: string | null;
  completed_at: string | null;
  reorder_of: string | null;
  created_at: string;
  updated_at: string;
};
export type OrdersInsert = {
  id?: string;
  ref: string;
  quote_id?: string | null;
  lead_id?: string | null;
  project_id?: string | null;
  customer_id?: string | null;
  contact?: Json;
  status?: OrderStatus;
  payment_status?: PaymentStatus;
  total_lak?: number | null;
  due_on?: string | null;
  delivery_method?: string;
  delivery_address?: string;
  customer_confirmed_at?: string | null;
  completed_at?: string | null;
  reorder_of?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type PageSectionsRow = {
  id: string;
  page_id: string;
  kind: string;
  props: Json;
  sort: number;
  updated_at: string;
};
export type PageSectionsInsert = {
  id?: string;
  page_id: string;
  kind: string;
  props?: Json;
  sort?: number;
  updated_at?: string;
};

export type PagesRow = {
  id: string;
  slug: string;
  title: string;
  seo: Json;
  status: PublishStatus;
  publish_at: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};
export type PagesInsert = {
  id?: string;
  slug: string;
  title: string;
  seo?: Json;
  status?: PublishStatus;
  publish_at?: string | null;
  created_by?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type PortfolioProjectsRow = {
  id: string;
  slug: string;
  title: string;
  client: string;
  sector: string;
  year: number;
  services: string[];
  summary: string;
  is_sample: boolean;
  featured: boolean;
  palette: string[];
  study: Json;
  impact: Json;
  cover_media_id: string | null;
  sort: number;
  status: PublishStatus;
  updated_at: string;
};
export type PortfolioProjectsInsert = {
  id?: string;
  slug: string;
  title: string;
  client?: string;
  sector?: string;
  year?: number;
  services?: string[];
  summary?: string;
  is_sample?: boolean;
  featured?: boolean;
  palette?: string[];
  study?: Json;
  impact?: Json;
  cover_media_id?: string | null;
  sort?: number;
  status?: PublishStatus;
  updated_at?: string;
};

export type PreordersRow = {
  id: string;
  ref: string;
  product_id: string | null;
  campaign_id: string | null;
  customer_id: string | null;
  lead_id: string | null;
  contact: Json;
  variant: string;
  qty: number;
  window_closes_on: string | null;
  status: string;
  created_at: string;
};
export type PreordersInsert = {
  id?: string;
  ref: string;
  product_id?: string | null;
  campaign_id?: string | null;
  customer_id?: string | null;
  lead_id?: string | null;
  contact?: Json;
  variant?: string;
  qty: number;
  window_closes_on?: string | null;
  status?: string;
  created_at?: string;
};

export type PricingRulesRow = {
  id: string;
  product_id: string | null;
  kind: string;
  label: string;
  match: Json;
  amount: number;
  amount_type: string;
  min_qty: number | null;
  max_qty: number | null;
  starts_at: string | null;
  ends_at: string | null;
  active: boolean;
  created_at: string;
  updated_at: string;
};
export type PricingRulesInsert = {
  id?: string;
  product_id?: string | null;
  kind: string;
  label: string;
  match?: Json;
  amount: number;
  amount_type: string;
  min_qty?: number | null;
  max_qty?: number | null;
  starts_at?: string | null;
  ends_at?: string | null;
  active?: boolean;
  created_at?: string;
  updated_at?: string;
};

export type ProductMediaRow = {
  product_id: string;
  media_id: string;
  sort: number;
};
export type ProductMediaInsert = {
  product_id: string;
  media_id: string;
  sort?: number;
};

export type ProductRelationsRow = {
  product_id: string;
  related_id: string;
  sort: number;
};
export type ProductRelationsInsert = {
  product_id: string;
  related_id: string;
  sort?: number;
};

export type ProductVariantsRow = {
  id: string;
  product_id: string;
  sku: string | null;
  name: string;
  attrs: Json;
  active: boolean;
  updated_at: string;
};
export type ProductVariantsInsert = {
  id?: string;
  product_id: string;
  sku?: string | null;
  name: string;
  attrs?: Json;
  active?: boolean;
  updated_at?: string;
};

export type ProductionJobsRow = {
  id: string;
  ref: string;
  order_id: string;
  order_item_id: string | null;
  product_name: string;
  qty: number;
  materials: string;
  print_method: string;
  design_id: string | null;
  final_artwork_version: number | null;
  final_artwork_path: string | null;
  deadline: string | null;
  notes: string;
  assigned_to: string | null;
  status: ProductionStatus;
  blocked_reason: string | null;
  started_at: string | null;
  finished_at: string | null;
  created_at: string;
  updated_at: string;
};
export type ProductionJobsInsert = {
  id?: string;
  ref: string;
  order_id: string;
  order_item_id?: string | null;
  product_name: string;
  qty: number;
  materials?: string;
  print_method?: string;
  design_id?: string | null;
  final_artwork_version?: number | null;
  final_artwork_path?: string | null;
  deadline?: string | null;
  notes?: string;
  assigned_to?: string | null;
  status?: ProductionStatus;
  blocked_reason?: string | null;
  started_at?: string | null;
  finished_at?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type ProductionOrderItemsRow = {
  id: string | null;
  order_id: string | null;
  product_slug: string | null;
  product_name: string | null;
  design_id: string | null;
  design_version: number | null;
  qty: number | null;
  config: Json | null;
  sort: number | null;
};

export type ProductionOrdersRow = {
  id: string | null;
  ref: string | null;
  status: OrderStatus | null;
  due_on: string | null;
  delivery_method: string | null;
  delivery_address: string | null;
  contact_name: string | null;
  contact_company: string | null;
  created_at: string | null;
};

export type ProductsRow = {
  id: string;
  slug: string;
  name: string;
  category_id: string;
  summary: string;
  description: string;
  data: Json;
  moq: number;
  lead_min_days: number | null;
  lead_max_days: number | null;
  pricing_mode: PricingMode;
  price_from_lak: number | null;
  price_unit: string;
  featured: boolean;
  sort: number;
  status: PublishStatus;
  publish_at: string | null;
  cover_media_id: string | null;
  created_at: string;
  updated_at: string;
};
export type ProductsInsert = {
  id?: string;
  slug: string;
  name: string;
  category_id: string;
  summary?: string;
  description?: string;
  data?: Json;
  moq?: number;
  lead_min_days?: number | null;
  lead_max_days?: number | null;
  pricing_mode?: PricingMode;
  price_from_lak?: number | null;
  price_unit?: string;
  featured?: boolean;
  sort?: number;
  status?: PublishStatus;
  publish_at?: string | null;
  cover_media_id?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type ProfilesRow = {
  id: string;
  email: string;
  full_name: string;
  phone: string;
  role: AppRole;
  company_id: string | null;
  avatar_path: string | null;
  marketing_consent: boolean;
  created_at: string;
  updated_at: string;
};
export type ProfilesInsert = {
  id: string;
  email: string;
  full_name?: string;
  phone?: string;
  role?: AppRole;
  company_id?: string | null;
  avatar_path?: string | null;
  marketing_consent?: boolean;
  created_at?: string;
  updated_at?: string;
};

export type ProjectMilestonesRow = {
  id: string;
  project_id: string;
  title: string;
  due_on: string | null;
  done_at: string | null;
  sort: number;
};
export type ProjectMilestonesInsert = {
  id?: string;
  project_id: string;
  title: string;
  due_on?: string | null;
  done_at?: string | null;
  sort?: number;
};

export type ProjectTasksRow = {
  id: string;
  project_id: string;
  milestone_id: string | null;
  title: string;
  assignee: string | null;
  due_on: string | null;
  done_at: string | null;
  sort: number;
};
export type ProjectTasksInsert = {
  id?: string;
  project_id: string;
  milestone_id?: string | null;
  title: string;
  assignee?: string | null;
  due_on?: string | null;
  done_at?: string | null;
  sort?: number;
};

export type ProjectsRow = {
  id: string;
  ref: string;
  lead_id: string | null;
  consultation_id: string | null;
  customer_id: string | null;
  company_id: string | null;
  name: string;
  objective: string;
  scope: string;
  requirements: Json;
  stage: ProjectStage;
  due_on: string | null;
  owner_staff: string | null;
  blocked_reason: string | null;
  created_at: string;
  updated_at: string;
};
export type ProjectsInsert = {
  id?: string;
  ref: string;
  lead_id?: string | null;
  consultation_id?: string | null;
  customer_id?: string | null;
  company_id?: string | null;
  name: string;
  objective?: string;
  scope?: string;
  requirements?: Json;
  stage?: ProjectStage;
  due_on?: string | null;
  owner_staff?: string | null;
  blocked_reason?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type QrScansRow = {
  id: number;
  qr_id: string;
  at: string;
  session_id: string | null;
  ua_family: string | null;
  referrer: string | null;
};
export type QrScansInsert = {
  id?: number;
  qr_id: string;
  at?: string;
  session_id?: string | null;
  ua_family?: string | null;
  referrer?: string | null;
};

export type QualityChecksRow = {
  id: string;
  job_id: string;
  checklist: Json;
  result: QcResult;
  note: string;
  checked_by: string | null;
  checked_at: string;
};
export type QualityChecksInsert = {
  id?: string;
  job_id: string;
  checklist: Json;
  result: QcResult;
  note?: string;
  checked_by?: string | null;
  checked_at?: string;
};

export type QuoteItemsRow = {
  id: string;
  quote_id: string;
  product_id: string | null;
  product_slug: string;
  product_name: string;
  design_id: string | null;
  design_version: number | null;
  qty: number;
  config: Json;
  estimate_unit_lak: number | null;
  unit_price_lak: number | null;
  line_total_lak: number | null;
  note: string;
  sort: number;
};
export type QuoteItemsInsert = {
  id?: string;
  quote_id: string;
  product_id?: string | null;
  product_slug: string;
  product_name: string;
  design_id?: string | null;
  design_version?: number | null;
  qty: number;
  config?: Json;
  estimate_unit_lak?: number | null;
  unit_price_lak?: number | null;
  line_total_lak?: number | null;
  note?: string;
  sort?: number;
};

export type QuotesRow = {
  id: string;
  ref: string;
  lead_id: string | null;
  project_id: string | null;
  customer_id: string | null;
  contact: Json;
  kind: string;
  needed_by: string | null;
  needs_design_help: boolean;
  customer_notes: string;
  estimate_low_lak: number | null;
  estimate_high_lak: number | null;
  total_lak: number | null;
  valid_until: string | null;
  terms: string;
  status: QuoteStatus;
  reorder_of: string | null;
  sent_at: string | null;
  decided_at: string | null;
  created_at: string;
  updated_at: string;
};
export type QuotesInsert = {
  id?: string;
  ref: string;
  lead_id?: string | null;
  project_id?: string | null;
  customer_id?: string | null;
  contact?: Json;
  kind?: string;
  needed_by?: string | null;
  needs_design_help?: boolean;
  customer_notes?: string;
  estimate_low_lak?: number | null;
  estimate_high_lak?: number | null;
  total_lak?: number | null;
  valid_until?: string | null;
  terms?: string;
  status?: QuoteStatus;
  reorder_of?: string | null;
  sent_at?: string | null;
  decided_at?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type RateHitsRow = {
  bucket: string;
  ip: string;
  at: string;
};
export type RateHitsInsert = {
  bucket: string;
  ip: string;
  at?: string;
};

export type RefCountersRow = {
  kind: string;
  year: number;
  n: number;
};
export type RefCountersInsert = {
  kind: string;
  year: number;
  n?: number;
};

export type ServicesRow = {
  id: string;
  slug: string;
  name: string;
  verb: string;
  summary: string;
  body: string;
  deliverables: string[];
  product_slugs: string[];
  sort: number;
  status: PublishStatus;
  updated_at: string;
};
export type ServicesInsert = {
  id?: string;
  slug: string;
  name: string;
  verb?: string;
  summary?: string;
  body?: string;
  deliverables?: string[];
  product_slugs?: string[];
  sort?: number;
  status?: PublishStatus;
  updated_at?: string;
};

export type SettingsRow = {
  key: string;
  value: Json;
  is_public: boolean;
  updated_at: string;
  updated_by: string | null;
};
export type SettingsInsert = {
  key: string;
  value: Json;
  is_public?: boolean;
  updated_at?: string;
  updated_by?: string | null;
};

export type SolutionsRow = {
  id: string;
  slug: string;
  goal: string;
  prompt: string;
  summary: string;
  recommend: Json;
  bundle_slug: string | null;
  sort: number;
  status: PublishStatus;
  updated_at: string;
};
export type SolutionsInsert = {
  id?: string;
  slug: string;
  goal: string;
  prompt?: string;
  summary?: string;
  recommend?: Json;
  bundle_slug?: string | null;
  sort?: number;
  status?: PublishStatus;
  updated_at?: string;
};

export type TeamMembersRow = {
  id: string;
  name: string;
  title: string;
  bio: string;
  photo_media_id: string | null;
  sort: number;
  status: PublishStatus;
  updated_at: string;
};
export type TeamMembersInsert = {
  id?: string;
  name: string;
  title?: string;
  bio?: string;
  photo_media_id?: string | null;
  sort?: number;
  status?: PublishStatus;
  updated_at?: string;
};

export type TestimonialsRow = {
  id: string;
  quote: string;
  name: string;
  role: string;
  company: string;
  consent_recorded: boolean;
  sort: number;
  status: PublishStatus;
  updated_at: string;
};
export type TestimonialsInsert = {
  id?: string;
  quote: string;
  name: string;
  role?: string;
  company?: string;
  consent_recorded?: boolean;
  sort?: number;
  status?: PublishStatus;
  updated_at?: string;
};

export type Tables = {
  abandoned_activities: AbandonedActivitiesRow;
  ai_usage: AiUsageRow;
  analytics_events: AnalyticsEventsRow;
  artwork_preflights: ArtworkPreflightsRow;
  attachments: AttachmentsRow;
  audit_log: AuditLogRow;
  billboard_availability: BillboardAvailabilityRow;
  billboard_bookings: BillboardBookingsRow;
  billboard_media: BillboardMediaRow;
  billboards: BillboardsRow;
  blog_posts: BlogPostsRow;
  brand_assets: BrandAssetsRow;
  brand_profiles: BrandProfilesRow;
  bundle_items: BundleItemsRow;
  bundles: BundlesRow;
  campaign_qr_codes: CampaignQrCodesRow;
  campaigns: CampaignsRow;
  categories: CategoriesRow;
  companies: CompaniesRow;
  consultations: ConsultationsRow;
  deliveries: DeliveriesRow;
  design_assets: DesignAssetsRow;
  design_templates: DesignTemplatesRow;
  design_versions: DesignVersionsRow;
  designs: DesignsRow;
  email_outbox: EmailOutboxRow;
  faqs: FaqsRow;
  feature_flags: FeatureFlagsRow;
  internal_notes: InternalNotesRow;
  lead_activities: LeadActivitiesRow;
  leads: LeadsRow;
  media: MediaRow;
  messages: MessagesRow;
  notifications: NotificationsRow;
  order_items: OrderItemsRow;
  orders: OrdersRow;
  page_sections: PageSectionsRow;
  pages: PagesRow;
  portfolio_projects: PortfolioProjectsRow;
  preorders: PreordersRow;
  pricing_rules: PricingRulesRow;
  product_media: ProductMediaRow;
  product_relations: ProductRelationsRow;
  product_variants: ProductVariantsRow;
  production_jobs: ProductionJobsRow;
  production_order_items: ProductionOrderItemsRow;
  production_orders: ProductionOrdersRow;
  products: ProductsRow;
  profiles: ProfilesRow;
  project_milestones: ProjectMilestonesRow;
  project_tasks: ProjectTasksRow;
  projects: ProjectsRow;
  qr_scans: QrScansRow;
  quality_checks: QualityChecksRow;
  quote_items: QuoteItemsRow;
  quotes: QuotesRow;
  rate_hits: RateHitsRow;
  ref_counters: RefCountersRow;
  services: ServicesRow;
  settings: SettingsRow;
  solutions: SolutionsRow;
  team_members: TeamMembersRow;
  testimonials: TestimonialsRow;
};
export type TableName = keyof Tables;
