import type { Category, PrintArea, Product, ProductColour, Service } from "../types";

export const categories: Category[] = [
  { slug: "apparel", name: "Apparel", plate: "01", order: 1, blurb: "T-shirts, polos, jerseys and uniforms — cut, printed and finished for teams of ten or ten thousand." },
  { slug: "accessories", name: "Caps, Bags & Umbrellas", plate: "02", order: 2, blurb: "The things people carry. Embroidered, printed and built to be seen in the street." },
  { slug: "promotional", name: "Promotional Products", plate: "03", order: 3, blurb: "Cups, pillows, blankets and giveaways that keep a brand in someone's hand." },
  { slug: "print", name: "Printed Materials", plate: "04", order: 4, blurb: "Posters, flyers, menus and stationery with colour you can trust." },
  { slug: "display", name: "Display & Events", plate: "05", order: 5, blurb: "A-boards, J-flags, kiosks and counters that set up in minutes and hold a crowd." },
  { slug: "signage", name: "Signage", plate: "06", order: 6, blurb: "Shopfronts, LED and vinyl. Designed, fabricated and installed." },
  { slug: "outdoor", name: "Outdoor Advertising", plate: "07", order: 7, blurb: "A billboard network across Laos, bookable by location and date." },
  { slug: "vehicle", name: "Vehicle Branding", plate: "08", order: 8, blurb: "Wraps and decals that turn a fleet into moving media." },
];

const core: ProductColour[] = [
  { name: "White", hex: "#f5f5f2" },
  { name: "Black", hex: "#17171a" },
  { name: "Navy", hex: "#1b2447" },
  { name: "Royal", hex: "#2a35d6" },
  { name: "Sky", hex: "#4db4e8" },
  { name: "Red", hex: "#d4302b" },
  { name: "Forest", hex: "#1f5a3d" },
  { name: "Yellow", hex: "#ffd60a" },
  { name: "Orange", hex: "#f2711c" },
  { name: "Heather", hex: "#9a9da3" },
  { name: "Sand", hex: "#d8cbb0" },
  { name: "Maroon", hex: "#6b1f2a" },
];

const apparelSizes = ["XS", "S", "M", "L", "XL", "2XL", "3XL"];

const chest: PrintArea = { key: "front", label: "Front", widthMm: 300, heightMm: 400 };
const back: PrintArea = { key: "back", label: "Back", widthMm: 320, heightMm: 420 };
const lSleeve: PrintArea = { key: "left-sleeve", label: "Left sleeve", widthMm: 90, heightMm: 90 };
const rSleeve: PrintArea = { key: "right-sleeve", label: "Right sleeve", widthMm: 90, heightMm: 90 };

export const products: Product[] = [
  {
    slug: "custom-t-shirt",
    name: "Custom T-Shirt",
    category: "apparel",
    summary: "Combed cotton tee, printed front, back and sleeve.",
    description:
      "Our most-ordered garment. A mid-weight combed cotton tee that holds its shape through wash after wash, printed with the method that suits your artwork — screen for bold spot colour, DTF for photographic detail, sublimation for all-over sportswear.",
    materials: ["100% combed cotton, 180 gsm", "Cotton/poly blend, 160 gsm", "Dry-fit polyester, 140 gsm"],
    sizes: apparelSizes,
    colours: core,
    printMethods: ["screen", "dtf", "sublimation"],
    customisation: ["Front, back and sleeve print", "Neck label", "Individual names & numbers", "Pantone-matched ink"],
    useCases: ["Events & festivals", "Staff uniforms", "School & university", "Merchandise", "Campaign giveaways"],
    moq: 12,
    leadTimeDays: [5, 10],
    pricingMode: "estimated",
    priceFromLak: 55000,
    priceUnit: "per piece",
    studio: { garment: "tee", areas: [chest, back, lSleeve, rSleeve] },
    related: ["polo-shirt", "sports-cap", "tote-bag"],
    featured: true,
    order: 1,
    seo: {
      title: "Custom T-Shirt Printing in Laos",
      description: "Design your own T-shirt online, preview front and back, and request a quote. Screen, DTF and sublimation printing in Vientiane with a 12-piece minimum.",
    },
  },
  {
    slug: "polo-shirt",
    name: "Polo Shirt",
    category: "apparel",
    summary: "Piqué polo for uniforms, embroidered or printed.",
    description:
      "The corporate standard. A structured piqué polo with a clean placket and a collar that stays flat, finished with embroidery on the chest or a full back print. Built for daily wear by hotel, bank, restaurant and retail teams.",
    materials: ["Cotton piqué, 220 gsm", "Poly-cotton piqué, 200 gsm", "Dry-fit piqué, 180 gsm"],
    sizes: apparelSizes,
    colours: core,
    printMethods: ["embroidery", "screen", "dtf"],
    customisation: ["Chest embroidery", "Back print", "Sleeve flag or logo", "Contrast collar & placket", "Individual names"],
    useCases: ["Corporate uniforms", "Hospitality", "Retail teams", "Schools", "Golf & events"],
    moq: 12,
    leadTimeDays: [7, 14],
    pricingMode: "estimated",
    priceFromLak: 80000,
    priceUnit: "per piece",
    studio: { garment: "polo", areas: [{ ...chest, widthMm: 260, heightMm: 300 }, back, lSleeve, rSleeve] },
    related: ["custom-t-shirt", "sports-cap", "fabric-face-mask"],
    featured: true,
    order: 2,
    seo: { title: "Custom Polo Shirts & Uniforms in Laos", description: "Embroidered and printed polo shirts for corporate, hospitality and school uniforms. Preview your logo on the garment and request a bulk quote." },
  },
  {
    slug: "sleeveless-jersey",
    name: "Sleeveless Jersey",
    category: "apparel",
    summary: "Lightweight sports singlet with all-over sublimation.",
    description:
      "A breathable sleeveless jersey for football, basketball, running clubs and outdoor work. Sublimation printing dyes the fibre itself, so colour never cracks, peels or fades — and every piece can carry its own name and number.",
    materials: ["Dry-fit polyester mesh, 140 gsm", "Interlock polyester, 150 gsm"],
    sizes: apparelSizes,
    colours: core,
    printMethods: ["sublimation", "dtf"],
    customisation: ["All-over print", "Names & numbers", "Sponsor panels", "Matching shorts on request"],
    useCases: ["Sports teams", "Running events", "Outdoor crews", "School sports days"],
    moq: 10,
    leadTimeDays: [7, 12],
    pricingMode: "estimated",
    priceFromLak: 45000,
    priceUnit: "per piece",
    studio: { garment: "sleeveless", areas: [{ ...chest, widthMm: 280 }, { ...back, widthMm: 280 }] },
    related: ["custom-t-shirt", "uv-arm-sleeve", "sports-cap"],
    featured: false,
    order: 3,
  },
  {
    slug: "uv-arm-sleeve",
    name: "UV Arm Sleeve",
    category: "apparel",
    summary: "SPF 50+ sleeve for riders, farmers and athletes.",
    description:
      "A full-arm compression sleeve in cool-touch fabric rated SPF 50+. A staple for motorbike riders and outdoor workers across Laos, and one of the most cost-effective branded items we make.",
    materials: ["Cool-touch nylon/spandex", "Polyester/spandex"],
    sizes: ["S/M", "L/XL"],
    colours: core.slice(0, 6),
    printMethods: ["sublimation", "dtf"],
    customisation: ["Logo print", "All-over pattern", "Branded packaging"],
    useCases: ["Delivery riders", "Agriculture", "Sports", "Promotional giveaways"],
    moq: 50,
    leadTimeDays: [7, 12],
    pricingMode: "estimated",
    priceFromLak: 35000,
    priceUnit: "per pair",
    studio: null,
    related: ["sleeveless-jersey", "sports-cap"],
    featured: false,
    order: 4,
  },
  {
    slug: "sports-cap",
    name: "Cap",
    category: "accessories",
    summary: "Snapback, fitted or trucker — embroidered front panel.",
    description:
      "Structured six-panel caps, five-panel truckers and classic snapbacks. 3D-puff or flat embroidery on the front panel, with optional side and back hits.",
    materials: ["Cotton twill", "Polyester mesh back", "Brushed cotton"],
    sizes: ["Adjustable"],
    colours: core.slice(0, 8),
    printMethods: ["embroidery", "dtf"],
    customisation: ["Front embroidery", "Side & back embroidery", "Woven label", "Custom strap"],
    useCases: ["Uniforms", "Merchandise", "Events", "Outdoor crews"],
    moq: 12,
    leadTimeDays: [7, 14],
    pricingMode: "estimated",
    priceFromLak: 40000,
    priceUnit: "per piece",
    studio: { garment: "cap", areas: [{ key: "panel", label: "Front panel", widthMm: 110, heightMm: 55 }] },
    related: ["custom-t-shirt", "polo-shirt"],
    featured: true,
    order: 5,
  },
  {
    slug: "tote-bag",
    name: "Tote Bag",
    category: "accessories",
    summary: "Cotton or non-woven tote with a large print panel.",
    description:
      "A reusable tote is a walking billboard with a long life. Choose heavy natural canvas for retail, or economical non-woven for high-volume giveaways.",
    materials: ["Natural cotton canvas, 280 gsm", "Non-woven polypropylene, 80 gsm"],
    sizes: ["38 × 42 cm", "35 × 40 cm with gusset"],
    colours: [
      { name: "Natural", hex: "#e6dcc5" },
      { name: "Black", hex: "#17171a" },
      { name: "Navy", hex: "#1b2447" },
      { name: "Red", hex: "#d4302b" },
    ],
    printMethods: ["screen", "dtf"],
    customisation: ["One or two-sided print", "Long or short handles", "Inner pocket"],
    useCases: ["Retail", "Conferences", "Eco campaigns", "Gift sets"],
    moq: 50,
    leadTimeDays: [7, 12],
    pricingMode: "estimated",
    priceFromLak: 25000,
    priceUnit: "per piece",
    studio: { garment: "tote", areas: [{ key: "front", label: "Front", widthMm: 280, heightMm: 300 }, { key: "back", label: "Back", widthMm: 280, heightMm: 300 }] },
    related: ["custom-t-shirt", "umbrella"],
    featured: true,
    order: 6,
  },
  {
    slug: "umbrella",
    name: "Branded Umbrella",
    category: "accessories",
    summary: "Golf, folding and café parasols with panel printing.",
    description:
      "From hand-held golf umbrellas to two-metre café parasols. Logos are printed per panel, so a single umbrella can carry your mark on every side.",
    materials: ["Pongee polyester canopy", "Fibreglass ribs", "Steel or aluminium shaft"],
    sizes: ['21" folding', '27" golf', '30" golf', "2 m parasol"],
    colours: core.slice(0, 8),
    printMethods: ["screen", "sublimation"],
    customisation: ["1–8 panel print", "Inner canopy print", "Branded sleeve"],
    useCases: ["Hotels & resorts", "Banks", "Cafés & restaurants", "Rainy-season promotions"],
    moq: 50,
    leadTimeDays: [14, 25],
    pricingMode: "quote",
    priceFromLak: null,
    priceUnit: "per piece",
    studio: null,
    related: ["tote-bag", "cup-print"],
    featured: false,
    order: 7,
  },
  {
    slug: "cup-print",
    name: "Cup Screen Printing",
    category: "promotional",
    summary: "Branded cups and sleeves for cafés and events.",
    description:
      "Screen-printed paper and PET cups, cup sleeves and lids. The highest-frequency brand touchpoint a café owns — every drink becomes an advertisement that leaves the shop.",
    materials: ["PET cold cups", "Double-wall paper cups", "Kraft sleeves"],
    sizes: ["8 oz", "12 oz", "16 oz", "22 oz"],
    colours: [],
    printMethods: ["screen", "offset"],
    customisation: ["1–4 colour print", "Full-wrap artwork", "Seasonal editions"],
    useCases: ["Cafés", "Bubble tea", "Restaurants", "Festivals"],
    moq: 1000,
    leadTimeDays: [10, 18],
    pricingMode: "quote",
    priceFromLak: null,
    priceUnit: "per 1,000",
    studio: null,
    related: ["tote-bag", "poster"],
    featured: false,
    order: 8,
  },
  {
    slug: "custom-pillow",
    name: "Photo-Print Pillow",
    category: "promotional",
    summary: "Full-colour printed cushions for retail and gifting.",
    description: "Soft-touch cushions printed edge to edge in full colour. Popular for hotel gifting, retail lines and mascots.",
    materials: ["Velvet-touch polyester cover", "PP cotton fill"],
    sizes: ["35 × 35 cm", "45 × 45 cm", "Custom shape"],
    colours: [],
    printMethods: ["sublimation"],
    customisation: ["Double-sided print", "Custom shape cut", "Zip cover"],
    useCases: ["Gifts", "Hotels", "Retail", "Mascots"],
    moq: 20,
    leadTimeDays: [7, 12],
    pricingMode: "estimated",
    priceFromLak: 50000,
    priceUnit: "per piece",
    studio: null,
    related: ["fleece-blanket"],
    featured: false,
    order: 9,
  },
  {
    slug: "fleece-blanket",
    name: "Printed Fleece Blanket",
    category: "promotional",
    summary: "Soft fleece with full-bleed custom printing.",
    description: "A premium cool-season gift. Full-bleed sublimation on soft fleece, folded and ribboned or boxed with your branding.",
    materials: ["Polar fleece", "Flannel fleece"],
    sizes: ["100 × 150 cm", "150 × 200 cm"],
    colours: [],
    printMethods: ["sublimation"],
    customisation: ["Full-bleed print", "Embroidered corner", "Gift packaging"],
    useCases: ["Corporate gifts", "Hotels", "Wholesale"],
    moq: 20,
    leadTimeDays: [10, 15],
    pricingMode: "estimated",
    priceFromLak: 120000,
    priceUnit: "per piece",
    studio: null,
    related: ["custom-pillow"],
    featured: false,
    order: 10,
  },
  {
    slug: "fabric-face-mask",
    name: "Fabric Face Mask",
    category: "promotional",
    summary: "Washable printed masks for teams and giveaways.",
    description: "Two and three-layer washable masks with logo or all-over print. Low cost, high visibility.",
    materials: ["Cotton outer", "Polyester outer with cotton lining"],
    sizes: ["Adult", "Child"],
    colours: core.slice(0, 6),
    printMethods: ["sublimation", "dtf"],
    customisation: ["Logo print", "All-over pattern", "Individual packaging"],
    useCases: ["Corporate", "Clinics", "Dust-season campaigns"],
    moq: 100,
    leadTimeDays: [5, 10],
    pricingMode: "estimated",
    priceFromLak: 8000,
    priceUnit: "per piece",
    studio: null,
    related: ["polo-shirt"],
    featured: false,
    order: 11,
  },
  {
    slug: "poster",
    name: "Posters & Flyers",
    category: "print",
    summary: "Offset and digital print from A5 to A0.",
    description: "Short-run digital for next-day needs, offset for volume. Colour-managed on coated, uncoated and synthetic stocks.",
    materials: ["Art paper 128–300 gsm", "Uncoated offset", "Synthetic waterproof"],
    sizes: ["A5", "A4", "A3", "A2", "A1", "A0"],
    colours: [],
    printMethods: ["offset", "large-format"],
    customisation: ["Matt / gloss lamination", "Spot UV", "Folding & creasing"],
    useCases: ["Promotions", "Menus", "Events", "Retail point-of-sale"],
    moq: 50,
    leadTimeDays: [2, 7],
    pricingMode: "quote",
    priceFromLak: null,
    priceUnit: "per run",
    studio: null,
    related: ["a-board", "vinyl-banner"],
    featured: false,
    order: 12,
  },
  {
    slug: "a-board",
    name: "A-Board",
    category: "display",
    summary: "Double-sided pavement sign with swappable prints.",
    description: "A weighted, double-sided pavement sign. Prints slide out, so one frame serves every promotion you run this year.",
    materials: ["Powder-coated steel frame", "Aluminium snap frame", "PVC print panels"],
    sizes: ["A1", "A0", "60 × 90 cm"],
    colours: [],
    printMethods: ["large-format", "uv"],
    customisation: ["Swappable inserts", "Header panel", "Water-fill base"],
    useCases: ["Cafés", "Retail", "Events", "Way-finding"],
    moq: 1,
    leadTimeDays: [5, 10],
    pricingMode: "quote",
    priceFromLak: null,
    priceUnit: "per unit",
    studio: null,
    related: ["j-flag", "poster"],
    featured: false,
    order: 13,
  },
  {
    slug: "j-flag",
    name: "J-Flag",
    category: "display",
    summary: "Feather flags that catch wind and attention.",
    description: "Tall, curved feather flags on a flexible pole. Visible from the far end of the street and packed into a bag small enough for a motorbike.",
    materials: ["Knitted polyester flag", "Fibreglass pole", "Cross base, spike or water base"],
    sizes: ["2.5 m", "3.5 m", "4.5 m"],
    colours: [],
    printMethods: ["sublimation"],
    customisation: ["Single or double-sided", "Base type", "Carry bag"],
    useCases: ["Showrooms", "Events", "Openings", "Roadside promotion"],
    moq: 2,
    leadTimeDays: [5, 10],
    pricingMode: "quote",
    priceFromLak: null,
    priceUnit: "per set",
    studio: null,
    related: ["a-board", "promo-counter"],
    featured: false,
    order: 14,
  },
  {
    slug: "promo-counter",
    name: "Kiosk & Promotion Counter",
    category: "display",
    summary: "Portable sampling counters and branded kiosks.",
    description: "Fold-flat promotion counters for sampling teams, through to fabricated kiosks for malls and events. Designed around how your staff actually stand, store and serve.",
    materials: ["PP / ABS portable counter", "Aluminium frame", "Custom MDF & acrylic fabrication"],
    sizes: ["Portable 80 × 40 × 200 cm", "Custom build"],
    colours: [],
    printMethods: ["large-format", "uv", "vinyl-cut"],
    customisation: ["Header board", "Shelving", "Lighting", "Full custom fabrication"],
    useCases: ["Product sampling", "Mall activations", "Trade fairs", "Bank & telco sign-ups"],
    moq: 1,
    leadTimeDays: [7, 21],
    pricingMode: "quote",
    priceFromLak: null,
    priceUnit: "per unit",
    studio: null,
    related: ["j-flag", "a-board"],
    featured: false,
    order: 15,
  },
  {
    slug: "vinyl-banner",
    name: "Vinyl Banner & Roll-Up",
    category: "signage",
    summary: "Large-format banners, roll-up stands and wall graphics.",
    description: "Outdoor-grade vinyl with welded hems and eyelets, retractable roll-up stands, and adhesive wall graphics — printed at large-format resolution with UV-stable inks.",
    materials: ["Frontlit PVC 440 gsm", "Blockout PVC", "Mesh PVC", "Adhesive vinyl"],
    sizes: ["Roll-up 80 × 200 cm", "Custom to 5 m wide"],
    colours: [],
    printMethods: ["large-format"],
    customisation: ["Hems & eyelets", "Pole pockets", "Roll-up cassette"],
    useCases: ["Shops", "Events", "Construction hoardings", "Exhibitions"],
    moq: 1,
    leadTimeDays: [2, 5],
    pricingMode: "estimated",
    priceFromLak: 80000,
    priceUnit: "per m²",
    studio: null,
    related: ["a-board", "led-signage"],
    featured: false,
    order: 16,
  },
  {
    slug: "led-signage",
    name: "LED & Shopfront Signage",
    category: "signage",
    summary: "Illuminated letters, lightboxes and fascia signs.",
    description: "Channel letters, lightboxes and full fascia builds — surveyed, designed, fabricated and installed by one team. High-brightness LEDs with low running cost and long service life.",
    materials: ["Acrylic faces", "Aluminium composite", "Stainless returns", "High-efficiency LED modules"],
    sizes: ["Made to measure"],
    colours: [],
    printMethods: ["uv", "vinyl-cut"],
    customisation: ["Front-lit, halo or edge-lit", "Site survey", "Installation & maintenance"],
    useCases: ["Shopfronts", "Offices", "Restaurants", "Hotels"],
    moq: 1,
    leadTimeDays: [10, 25],
    pricingMode: "quote",
    priceFromLak: null,
    priceUnit: "per project",
    studio: null,
    related: ["vinyl-banner", "billboard-rental"],
    featured: true,
    order: 17,
  },
  {
    slug: "billboard-rental",
    name: "Billboard Rental",
    category: "outdoor",
    summary: "Bookable billboard sites across the provinces of Laos.",
    description: "Choose a site on the SPP Outdoor Network map, preview your artwork on the structure, and request the dates you need. We print, install, maintain and report.",
    materials: ["Frontlit & backlit flex", "Steel monopole and rooftop structures"],
    sizes: ["6 × 3 m", "8 × 4 m", "10 × 5 m", "12 × 6 m", "14 × 7 m"],
    colours: [],
    printMethods: ["large-format"],
    customisation: ["Artwork design", "Print & installation", "QR campaign tracking", "Multi-site packages"],
    useCases: ["Brand launches", "Telecom & banking", "Tourism", "Government & NGO campaigns"],
    moq: 1,
    leadTimeDays: [7, 14],
    pricingMode: "estimated",
    priceFromLak: null,
    priceUnit: "per month",
    studio: null,
    related: ["led-signage", "vehicle-wrap"],
    featured: true,
    order: 18,
    seo: { title: "Billboard Rental & Outdoor Advertising in Laos", description: "Explore available billboard locations in Vientiane and across Laos on an interactive map. Preview your artwork and request a booking." },
  },
  {
    slug: "vehicle-wrap",
    name: "Vehicle Branding",
    category: "vehicle",
    summary: "Full wraps, partial wraps and fleet decals.",
    description: "Cast vinyl wraps for cars, vans, trucks and tuk-tuks. We template the vehicle, design to its panels, print, laminate and install.",
    materials: ["Cast wrap vinyl", "UV over-laminate", "Reflective & perforated window film"],
    sizes: ["Motorbike box", "Car", "Pickup", "Van", "Truck"],
    colours: [],
    printMethods: ["large-format", "vinyl-cut"],
    customisation: ["Full or partial wrap", "Fleet roll-out", "Removal & re-wrap"],
    useCases: ["Delivery fleets", "Service vehicles", "Food trucks", "Campaign vehicles"],
    moq: 1,
    leadTimeDays: [5, 12],
    pricingMode: "quote",
    priceFromLak: null,
    priceUnit: "per vehicle",
    studio: null,
    related: ["billboard-rental", "led-signage"],
    featured: false,
    order: 19,
  },
];

export const services: Service[] = [
  {
    slug: "graphic-design",
    name: "Graphic Design & Mockups",
    verb: "Design",
    order: 1,
    summary: "Logos, artwork and print-ready files — made by people who know how it will be produced.",
    body: "Design that ignores production gets rebuilt at the press. Ours starts from the garment, the substrate and the viewing distance, so what you approve is what gets made.",
    deliverables: ["Logo & identity refinement", "Apparel and merchandise artwork", "Billboard & signage layouts", "Print-ready file preparation", "Photoreal mockups"],
    products: ["custom-t-shirt", "polo-shirt", "poster"],
  },
  {
    slug: "visualisation",
    name: "SPP Studio & Visualisation",
    verb: "Visualise",
    order: 2,
    summary: "See it on the shirt, on the street and on the billboard before a single metre is printed.",
    body: "SPP Studio lets you build a front-and-back mockup in your browser, then place it in the real world. Approvals get faster because nobody has to imagine anything.",
    deliverables: ["Online mockup designer", "Front / back / sleeve previews", "Billboard artwork preview", "Watermarked downloads with Design ID"],
    products: ["custom-t-shirt", "polo-shirt", "sports-cap", "tote-bag", "billboard-rental"],
  },
  {
    slug: "production",
    name: "Apparel & Print Production",
    verb: "Produce",
    order: 3,
    summary: "Screen, DTF, sublimation, embroidery, offset and large-format under one roof.",
    body: "One team owns the job from artwork check to quality control. Every order moves through the same tracked stages, so you always know where it is.",
    deliverables: ["Garment manufacture & decoration", "Promotional product sourcing", "Offset & digital print", "Large-format & signage fabrication", "Quality control and packing"],
    products: ["custom-t-shirt", "polo-shirt", "cup-print", "vinyl-banner", "led-signage"],
  },
  {
    slug: "outdoor-advertising",
    name: "Outdoor & Campaigns",
    verb: "Promote",
    order: 4,
    summary: "Billboards, vehicles and events — planned as one campaign and measured with QR tracking.",
    body: "A shirt, a banner and a billboard are stronger together. We plan the physical campaign as a system and attach QR tracking so you can see what the street sent you.",
    deliverables: ["Billboard site planning & booking", "Installation & maintenance", "Vehicle branding", "Event display systems", "QR campaign tracking"],
    products: ["billboard-rental", "vehicle-wrap", "j-flag", "promo-counter"],
  },
];
