/**
 * Generates supabase/seed.sql from src/content/seed — the same data that
 * builds the static site before a database exists. Idempotent (upserts).
 *   npx tsx scripts/build-seed.ts
 */
import { writeFileSync } from "node:fs";
import { seed } from "../src/content/seed";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${String(v).replace(/'/g, "''")}'`;
};
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (v: string[]) => `array[${v.map(q).join(",")}]::text[]`;

const out: string[] = [
  "-- GENERATED by scripts/build-seed.ts — do not edit by hand.",
  "begin;",
  `insert into settings(key, value, is_public) values ('site', ${j(seed.settings)}, true) on conflict (key) do update set value = excluded.value;`,
];

const flagNotes: Record<string, string> = {
  AI_DESIGN: "SPP AI Design Assistant inside Studio",
  MOCKUP_STUDIO: "SPP Studio mockup designer",
  BILLBOARD_BOOKING: "Billboard booking requests",
  ONLINE_PRICING: "Show instant estimates on the public site",
  PREORDERS: "Preorder windows on campaigns",
  CUSTOMER_PORTAL: "Customer accounts (My SPP)",
  PAYMENTS: "Online payments (not yet implemented)",
  PRODUCTION_WORKFLOW: "Production jobs, QC and delivery",
};
for (const [k, v] of Object.entries(seed.flags))
  out.push(`insert into feature_flags(key, enabled, description) values (${q(k)}, ${q(v)}, ${q(flagNotes[k] ?? "")}) on conflict (key) do nothing;`);

for (const c of seed.categories)
  out.push(`insert into categories(slug, name, blurb, plate, sort) values (${q(c.slug)}, ${q(c.name)}, ${q(c.blurb)}, ${q(c.plate)}, ${c.order}) on conflict (slug) do update set name = excluded.name, blurb = excluded.blurb, plate = excluded.plate, sort = excluded.sort;`);

for (const p of seed.products) {
  const data = { materials: p.materials, sizes: p.sizes, colours: p.colours, printMethods: p.printMethods, customisation: p.customisation, useCases: p.useCases, studio: p.studio, seo: p.seo ?? {} };
  out.push(
    `insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values (${q(p.slug)}, ${q(p.name)}, (select id from categories where slug = ${q(p.category)}), ${q(p.summary)}, ${q(p.description)}, ${j(data)}, ${p.moq}, ${q(p.leadTimeDays?.[0] ?? null)}, ${q(p.leadTimeDays?.[1] ?? null)}, ${q(p.pricingMode)}, ${q(p.priceFromLak)}, ${q(p.priceUnit)}, ${q(p.featured)}, ${p.order}, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;`,
  );
}
for (const p of seed.products)
  p.related.forEach((r, i) =>
    out.push(`insert into product_relations(product_id, related_id, sort) select a.id, b.id, ${i} from products a, products b where a.slug = ${q(p.slug)} and b.slug = ${q(r)} on conflict do nothing;`),
  );

// Pricing rules. Seeded from the previous site's public LAK ranges: the top of
// each range becomes the MOQ price, and volume tiers walk down toward the
// bottom of it. SPP should review every figure in Command Center → Pricing.
const ranges: Record<string, [number, number]> = {
  "custom-t-shirt": [55000, 120000], "polo-shirt": [80000, 150000], "sleeveless-jersey": [45000, 90000], "uv-arm-sleeve": [35000, 65000],
  "sports-cap": [40000, 80000], "tote-bag": [25000, 55000], "custom-pillow": [50000, 90000], "fleece-blanket": [120000, 220000],
  "fabric-face-mask": [8000, 20000], "vinyl-banner": [80000, 150000],
};
out.push("delete from pricing_rules where label like 'seed:%';");
for (const [slug, [lo, hi]] of Object.entries(ranges)) {
  const pid = `(select id from products where slug = ${q(slug)})`;
  const full = Math.round(((lo / hi - 1) * 100) * 10) / 10; // deepest discount reaches the low end
  out.push(`insert into pricing_rules(product_id, kind, label, amount, amount_type) values (${pid}, 'base', 'seed:base', ${hi}, 'per_unit');`);
  const tiers: [number, number | null, number][] = [[50, 99, full * 0.3], [100, 249, full * 0.5], [250, 499, full * 0.7], [500, 999, full * 0.85], [1000, null, full]];
  for (const [min, max, pct] of tiers)
    out.push(`insert into pricing_rules(product_id, kind, label, amount, amount_type, min_qty, max_qty) values (${pid}, 'qty_tier', 'seed:tier ${min}+', ${pct.toFixed(1)}, 'percent', ${min}, ${q(max)});`);
}
out.push(
  `insert into pricing_rules(product_id, kind, label, match, amount, amount_type) values (null, 'method', 'seed:Embroidery', '{"method":"embroidery"}', 12, 'percent');`,
  `insert into pricing_rules(product_id, kind, label, match, amount, amount_type) values (null, 'method', 'seed:Sublimation (all-over)', '{"method":"sublimation"}', 8, 'percent');`,
  `insert into pricing_rules(product_id, kind, label, amount, amount_type) values (null, 'location', 'seed:Extra print location', 9000, 'per_unit');`,
  `insert into pricing_rules(product_id, kind, label, amount, amount_type) values (null, 'rush', 'seed:Rush production', 25, 'percent');`,
  `insert into pricing_rules(product_id, kind, label, amount, amount_type) values (null, 'delivery', 'seed:Delivery (Vientiane)', 50000, 'flat');`,
);

for (const s of seed.services)
  out.push(`insert into services(slug, name, verb, summary, body, deliverables, product_slugs, sort) values (${q(s.slug)}, ${q(s.name)}, ${q(s.verb)}, ${q(s.summary)}, ${q(s.body)}, ${arr(s.deliverables)}, ${arr(s.products)}, ${s.order}) on conflict (slug) do update set name = excluded.name, summary = excluded.summary, body = excluded.body, deliverables = excluded.deliverables, product_slugs = excluded.product_slugs;`);
for (const s of seed.solutions)
  out.push(`insert into solutions(slug, goal, prompt, summary, recommend, bundle_slug, sort) values (${q(s.slug)}, ${q(s.goal)}, ${q(s.prompt)}, ${q(s.summary)}, ${j(s.recommend)}, ${q(s.bundle ?? null)}, ${s.order}) on conflict (slug) do update set goal = excluded.goal, recommend = excluded.recommend;`);
for (const b of seed.bundles) {
  out.push(`insert into bundles(slug, name, summary, discount_pct, featured) values (${q(b.slug)}, ${q(b.name)}, ${q(b.summary)}, ${b.discountPct}, ${q(b.featured)}) on conflict (slug) do update set name = excluded.name, summary = excluded.summary, discount_pct = excluded.discount_pct;`);
  out.push(`delete from bundle_items where bundle_id = (select id from bundles where slug = ${q(b.slug)});`);
  b.items.forEach((it, i) => out.push(`insert into bundle_items(bundle_id, product_id, qty, note, sort) values ((select id from bundles where slug = ${q(b.slug)}), (select id from products where slug = ${q(it.product)}), ${it.qty}, ${q(it.note ?? "")}, ${i});`));
}
for (const b of seed.billboards)
  out.push(
    `insert into billboards(code, name, province, district, address, lat, lng, width_m, height_m, orientation, faces, facing, lit, visibility, traffic, status, available_from, pricing_mode, price_from_usd_month, min_months, installation, description, verified)
     values (${q(b.code)}, ${q(b.name)}, ${q(b.province)}, ${q(b.district)}, ${q(b.address)}, ${b.lat}, ${b.lng}, ${b.widthM}, ${b.heightM}, ${q(b.orientation)}, ${b.faces}, ${q(b.facing)}, ${q(b.lit)}, ${q(b.visibility)}, ${q(b.traffic)}, ${q(b.status)}, ${q(b.availableFrom)}, ${q(b.pricingMode)}, ${q(b.priceFromUsdMonth)}, ${b.minMonths}, ${q(b.installation)}, ${q(b.description)}, ${q(b.verified)})
     on conflict (code) do nothing;`,
  );
seed.portfolio.forEach((p, i) =>
  out.push(`insert into portfolio_projects(slug, title, client, sector, year, services, summary, is_sample, featured, palette, study, impact, sort, status) values (${q(p.slug)}, ${q(p.title)}, ${q(p.client)}, ${q(p.sector)}, ${p.year}, ${arr(p.services)}, ${q(p.summary)}, ${q(p.isSample)}, ${q(p.featured)}, ${arr(p.palette)}, ${j(p.study)}, ${j(p.impact)}, ${i}, 'published') on conflict (slug) do nothing;`),
);
seed.faqs.forEach((f, i) => out.push(`insert into faqs(topic, q, a, sort) select ${q(f.topic)}, ${q(f.q)}, ${q(f.a)}, ${i} where not exists (select 1 from faqs where q = ${q(f.q)});`));
for (const p of seed.posts)
  out.push(`insert into blog_posts(slug, title, excerpt, body, tag, read_mins, status, published_at) values (${q(p.slug)}, ${q(p.title)}, ${q(p.excerpt)}, ${q(p.body)}, ${q(p.tag)}, ${p.readMins}, 'published', ${q(p.date)}) on conflict (slug) do nothing;`);
seed.templates.forEach((t, i) =>
  out.push(`insert into design_templates(slug, name, category, garments, suggested_colour, sides, featured, sort, status) values (${q(t.slug)}, ${q(t.name)}, ${q(t.category)}, ${arr(t.garments)}, ${q(t.suggestedColour)}, ${j(t.sides)}, ${q(t.featured)}, ${i}, 'published') on conflict (slug) do nothing;`),
);
out.push("commit;");
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n") + "\n");
console.log(`seed.sql written — ${out.length} statements`);
