/**
 * Rasterises the share image and the Apple touch icon from SVG composed here,
 * so both stay in step with the roundel geometry in src/components/brand/logo-paths.ts
 * (generated by scripts/build-logo.ts).
 *
 *   npx tsx scripts/build-og.ts
 *
 * Text is set in system fonts (librsvg cannot see the site's self-hosted
 * webfonts); the roundel itself is pure path data and renders identically anywhere.
 */
import { mkdir } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { ROUNDEL, ROUNDEL_ARC_TEXT, ROUNDEL_COLOURS as RC, ROUNDEL_LETTERS, ROUNDEL_RIGHT, ROUNDEL_SPLIT } from "../src/components/brand/logo-paths";
import { settings } from "../src/content/seed/settings";
import { BRAND } from "../src/lib/brand";

const root = path.resolve(__dirname, "..");
const INK = BRAND.ink;
const FOG = BRAND.white;
const GOLD = BRAND.gold;
const SANS = "'Helvetica Neue', Helvetica, Arial, sans-serif";
const SERIF = "'Times New Roman', Times, serif";
const MONO = "Menlo, 'SF Mono', 'Courier New', monospace";

const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;");

/** The roundel in a 100-unit box. */
const roundel = (id: string) =>
  `<defs><radialGradient id="${id}i" cx="35%" cy="30%" r="80%"><stop offset="0" stop-color="${RC.indigo}"/><stop offset="1" stop-color="${RC.indigoDeep}"/></radialGradient><linearGradient id="${id}s" x1="1" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${RC.skyLight}"/><stop offset="1" stop-color="${RC.sky}"/></linearGradient></defs>` +
  `<circle cx="${ROUNDEL.cx}" cy="${ROUNDEL.cy}" r="${ROUNDEL.r}" fill="url(#${id}i)"/><path d="${ROUNDEL_RIGHT}" fill="url(#${id}s)"/>` +
  `<path d="${ROUNDEL_SPLIT}" fill="none" stroke="#fff" stroke-width="1.8" stroke-linecap="round"/>` +
  `<g fill="${RC.gold}" stroke="${RC.goldDeep}" stroke-width=".7" stroke-linejoin="round" paint-order="stroke">${Object.values(ROUNDEL_LETTERS).map((d) => `<path d="${d}"/>`).join("")}</g>` +
  `<path d="${ROUNDEL_ARC_TEXT}" fill="#fff"/>`;

const [line1 = "", line2 = "", ...restWords] = settings.tagline.split(/(?<=\.)\s+/);
const line3 = restWords.join(" ");
const lastWord = line3.split(" ").pop() ?? "";
const line3Lead = line3.slice(0, line3.length - lastWord.length);

const og = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <defs>
    <pattern id="dots" width="12" height="12" patternUnits="userSpaceOnUse"><circle cx="6" cy="6" r="1.4" fill="${FOG}"/></pattern>
    <radialGradient id="fade" cx="82%" cy="30%" r="60%"><stop offset="0" stop-color="#fff" stop-opacity=".16"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient>
    <mask id="m"><rect width="1200" height="630" fill="url(#fade)"/></mask>
  </defs>
  <rect width="1200" height="630" fill="${INK}"/>
  <rect width="1200" height="630" fill="url(#dots)" mask="url(#m)"/>
  <g stroke="${BRAND.fogDim}" stroke-opacity=".6" stroke-width="2"><path d="M40 70H64M70 40V64M1160 70H1136M1130 40V64M40 560H64M70 590V566M1160 560H1136M1130 590V566"/></g>
  <g transform="translate(92 84) scale(1.6)">${roundel("og")}</g>
  <g fill="${FOG}"><text x="292" y="180" font-family="${SANS}" font-weight="800" font-size="92" letter-spacing="-4">SPP</text><text x="296" y="216" font-family="${MONO}" font-size="19" letter-spacing="4.5">SOLE CO., LTD</text></g>
  <g fill="none" stroke="${BRAND.sky}" stroke-width="2"><circle cx="1086" cy="122" r="16"/><path d="M1060 122H1112M1086 96V148"/></g>
  <g font-family="${SANS}" font-weight="700" font-size="76" letter-spacing="-3" fill="${FOG}">
    <text x="92" y="388">${esc(line1)} ${esc(line2)}</text>
    <text x="92" y="472">${esc(line3Lead)}<tspan font-family="${SERIF}" font-style="italic" font-weight="400" letter-spacing="-1" fill="${GOLD}">${esc(lastWord.toLowerCase())}</tspan></text>
  </g>
  <text x="96" y="548" font-family="${MONO}" font-size="19" letter-spacing="3.4" fill="${BRAND.fog}">APPAREL · PRINT · SIGNAGE · BILLBOARDS — ${esc(settings.address.city.toUpperCase())}, ${esc(settings.address.country.toUpperCase())}</text>
  <g transform="translate(0 618)"><rect width="300" height="12" fill="${BRAND.sky}"/><rect x="300" width="300" height="12" fill="${BRAND.violet}"/><rect x="600" width="300" height="12" fill="${GOLD}"/><rect x="900" width="300" height="12" fill="${BRAND.navy}"/></g>
</svg>`;

// Apple masks the corners itself; the roundel sits on the indigo ground with a little breathing room.
const apple = `<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180" viewBox="0 0 100 100">
  <rect width="100" height="100" fill="${INK}"/>
  <g transform="translate(6 6) scale(0.88)">${roundel("ap")}</g>
</svg>`;

async function main() {
  await mkdir(path.join(root, "public"), { recursive: true });
  await sharp(Buffer.from(og)).png({ compressionLevel: 9 }).toFile(path.join(root, "public/og.png"));
  await sharp(Buffer.from(apple), { density: 144 }).resize(180, 180).png({ compressionLevel: 9 }).toFile(path.join(root, "src/app/apple-icon.png"));
  process.stdout.write("wrote public/og.png (1200×630) and src/app/apple-icon.png (180×180)\n");
}

main().catch((e) => { process.stderr.write(`${(e as Error).message}\n`); process.exit(1); });
