/**
 * Generates the SPP roundel geometry as path data, so the logo renders identically
 * in React (SVG), on canvas (Studio exports), in librsvg (OG image, touch icon)
 * and in the downloadable brand files — with no font dependency anywhere.
 *
 *   npx tsx scripts/build-logo.ts
 *
 * The mark is SPP's existing logo, redrawn as vector from the company's printed
 * collateral: a circle split by a wave into deep indigo and sky blue, "SPP" in
 * gold italic serif stacked down the seam, and "SOLE CO., LTD" set along the base.
 * Letterforms come from Times New Roman Bold Italic / Arial Bold (the faces used
 * in the original) and are baked to outlines here.
 *
 * Writes: src/components/brand/logo-paths.ts, public/brand/*.svg, src/app/icon.svg
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import opentype from "opentype.js";

const root = path.resolve(__dirname, "..");
const FONTS = "/System/Library/Fonts/Supplemental";

const serif = opentype.loadSync(path.join(FONTS, "Times New Roman Bold Italic.ttf"));
const sans = opentype.loadSync(path.join(FONTS, "Arial Bold.ttf"));

const fmt = (n: number) => String(Math.round(n * 100) / 100);

type Cmd = opentype.PathCommand;
type Affine = (x: number, y: number) => [number, number];

function pathData(cmds: Cmd[], t: Affine): string {
  const out: string[] = [];
  for (const c of cmds) {
    if (c.type === "M" || c.type === "L") { const [x, y] = t(c.x, c.y); out.push(`${c.type}${fmt(x)} ${fmt(y)}`); }
    else if (c.type === "C") { const [x1, y1] = t(c.x1, c.y1); const [x2, y2] = t(c.x2, c.y2); const [x, y] = t(c.x, c.y); out.push(`C${fmt(x1)} ${fmt(y1)} ${fmt(x2)} ${fmt(y2)} ${fmt(x)} ${fmt(y)}`); }
    else if (c.type === "Q") { const [x1, y1] = t(c.x1, c.y1); const [x, y] = t(c.x, c.y); out.push(`Q${fmt(x1)} ${fmt(y1)} ${fmt(x)} ${fmt(y)}`); }
    else out.push("Z");
  }
  return out.join("");
}

/** A glyph run set on a straight baseline, in the 100-unit roundel space. */
function straight(font: opentype.Font, text: string, x: number, baseline: number, size: number): string {
  return pathData(font.getPath(text, x, baseline, size).commands, (px, py) => [px, py]);
}

/** A glyph run set along a circle, centred at `centreDeg` (90 = bottom), letter tops facing the centre. */
function arc(font: opentype.Font, text: string, cx: number, cy: number, r: number, size: number, centreDeg: number, tracking: number): string {
  const glyphs = font.stringToGlyphs(text);
  const scale = size / font.unitsPerEm;
  const widths = glyphs.map((g) => (g.advanceWidth ?? 0) * scale + tracking);
  const total = widths.reduce((a, b) => a + b, 0) - tracking;
  const toDeg = (len: number) => (len / r) * (180 / Math.PI);
  let theta = centreDeg + toDeg(total / 2);
  const parts: string[] = [];
  glyphs.forEach((g, i) => {
    const w = widths[i]! - tracking;
    const mid = theta - toDeg(w / 2);
    const rad = (mid * Math.PI) / 180;
    const px = cx + r * Math.cos(rad), py = cy + r * Math.sin(rad);
    const rot = ((mid - 90) * Math.PI) / 180;
    const cos = Math.cos(rot), sin = Math.sin(rot);
    const cmds = g.getPath(-w / 2, 0, size).commands;
    parts.push(pathData(cmds, (x, y) => [px + x * cos - y * sin, py + x * sin + y * cos]));
    theta -= toDeg(widths[i]!);
  });
  return parts.join("");
}

// ---- geometry (100 × 100 viewBox, circle r 48 at 50,50) --------------------
const R = 48, C = 50;
const yAt = (x: number) => C - Math.sqrt(R * R - (x - C) ** 2);
const top = { x: 60, y: yAt(60) };
const bottom = { x: 42, y: 100 - yAt(42) };
// The wave: from the top point it bows left through the upper half, back right
// through the lower half, then sweeps left again to the base.
const split = `M${fmt(top.x)} ${fmt(top.y)}C40 24 72 50 55 66S30 88 ${fmt(bottom.x)} ${fmt(bottom.y)}`;
// Sky region: the wave, then back up the right-hand rim of the circle.
const right = `${split}A${R} ${R} 0 0 0 ${fmt(top.x)} ${fmt(top.y)}Z`;

const letters = {
  s: straight(serif, "S", 22.5, 37, 34),
  p1: straight(serif, "P", 24.5, 60, 30),
  p2: straight(serif, "P", 22.5, 81.5, 30),
};
const arcText = arc(sans, "SOLE CO., LTD", C, C, 41.8, 5.9, 91, 0.5);

const ts = `/* Generated by scripts/build-logo.ts — do not edit by hand. */

/** The SPP roundel lives in a 100 × 100 box; the circle is r ${R} at (${C}, ${C}). */
export const ROUNDEL_VIEWBOX = "0 0 100 100";
export const ROUNDEL = { cx: ${C}, cy: ${C}, r: ${R} } as const;

/** The wave that divides indigo (left) from sky (right), top to bottom. */
export const ROUNDEL_SPLIT = ${JSON.stringify(split)};
/** The sky-blue region: the wave closed along the right-hand rim. */
export const ROUNDEL_RIGHT = ${JSON.stringify(right)};

/** "S", "P", "P" — Times New Roman Bold Italic, baked to outlines, positioned. */
export const ROUNDEL_LETTERS = {
  s: ${JSON.stringify(letters.s)},
  p1: ${JSON.stringify(letters.p1)},
  p2: ${JSON.stringify(letters.p2)},
} as const;

/** "SOLE CO., LTD" set along the base of the circle. */
export const ROUNDEL_ARC_TEXT = ${JSON.stringify(arcText)};

export const ROUNDEL_COLOURS = {
  indigo: "#2a1f8f",
  indigoDeep: "#150f57",
  sky: "#38b6f2",
  skyLight: "#8ddcfb",
  gold: "#f5b81f",
  goldDeep: "#b8820a",
  white: "#ffffff",
} as const;
`;

/** Standalone SVG of the roundel (full colour, or one-colour). */
function svgFile(variant: "colour" | "mono-ink" | "mono-white", title: string): string {
  const c = { indigo: "#2a1f8f", indigoDeep: "#150f57", sky: "#38b6f2", skyLight: "#8ddcfb", gold: "#f5b81f", goldDeep: "#b8820a" };
  const body =
    variant === "colour"
      ? `<defs>
    <radialGradient id="ind" cx="35%" cy="30%" r="80%"><stop offset="0" stop-color="${c.indigo}"/><stop offset="1" stop-color="${c.indigoDeep}"/></radialGradient>
    <linearGradient id="sky" x1="1" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${c.skyLight}"/><stop offset="1" stop-color="${c.sky}"/></linearGradient>
  </defs>
  <circle cx="${C}" cy="${C}" r="${R}" fill="url(#ind)"/>
  <path d="${right}" fill="url(#sky)"/>
  <path d="${split}" fill="none" stroke="#fff" stroke-width="1.8" stroke-linecap="round"/>
  <g fill="${c.gold}" stroke="${c.goldDeep}" stroke-width=".7" stroke-linejoin="round" paint-order="stroke"><path d="${letters.s}"/><path d="${letters.p1}"/><path d="${letters.p2}"/></g>
  <path d="${arcText}" fill="#fff"/>`
      : (() => {
          const ink = variant === "mono-ink" ? "#0b0e2c" : "#ffffff";
          const knock = variant === "mono-ink" ? "#ffffff" : "#0b0e2c";
          return `<circle cx="${C}" cy="${C}" r="${R}" fill="${ink}"/>
  <path d="${split}" fill="none" stroke="${knock}" stroke-width="1.8" stroke-linecap="round"/>
  <g fill="${knock}"><path d="${letters.s}"/><path d="${letters.p1}"/><path d="${letters.p2}"/><path d="${arcText}"/></g>`;
        })();
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="512" height="512" role="img" aria-labelledby="t">
  <title id="t">${title}</title>
  ${body}
</svg>
`;
}

async function main() {
  await mkdir(path.join(root, "public/brand"), { recursive: true });
  await writeFile(path.join(root, "src/components/brand/logo-paths.ts"), ts);
  await writeFile(path.join(root, "public/brand/spp-logo.svg"), svgFile("colour", "SPP Sole Co., Ltd — logo"));
  await writeFile(path.join(root, "public/brand/spp-logo-mono-ink.svg"), svgFile("mono-ink", "SPP logo — one colour, indigo"));
  await writeFile(path.join(root, "public/brand/spp-logo-mono-white.svg"), svgFile("mono-white", "SPP logo — one colour, white"));
  await writeFile(path.join(root, "src/app/icon.svg"), svgFile("colour", "SPP"));
  process.stdout.write("wrote logo-paths.ts, public/brand/spp-logo*.svg, src/app/icon.svg\n");
}

main().catch((e) => { process.stderr.write(`${(e as Error).message}\n`); process.exit(1); });
