/**
 * Generates src/lib/backend/db-types.ts by introspecting a throw-away Postgres
 * with every migration applied — so front-end row types can never drift from
 * the schema.   npx tsx scripts/gen-types.ts
 */
import EmbeddedPostgres from "embedded-postgres";
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import pg from "pg";

const root = new URL("..", import.meta.url).pathname;
const dir = mkdtempSync(join(tmpdir(), "spp-types-"));
const port = 54330;
const server = new EmbeddedPostgres({ databaseDir: dir, user: "postgres", password: "postgres", port, persistent: false, onLog: () => {}, onError: () => {} });

const scalar: Record<string, string> = {
  uuid: "string", text: "string", citext: "string", varchar: "string", bpchar: "string", inet: "string", date: "string", timestamptz: "string", timestamp: "string",
  int2: "number", int4: "number", int8: "number", float4: "number", float8: "number", numeric: "number", bool: "boolean", jsonb: "Json", json: "Json",
};
const pascal = (s: string) => s.replace(/(^|_)([a-z])/g, (_, __, c: string) => c.toUpperCase());

async function main() {
  await server.initialise();
  await server.start();
  await server.createDatabase("spp");
  const c = new pg.Client({ host: "localhost", port, user: "postgres", password: "postgres", database: "spp" });
  c.on("error", () => {});
  await c.connect();
  await c.query(`create role anon nologin; create role authenticated nologin; create schema auth;
    create table auth.users (id uuid primary key default gen_random_uuid(), email text, raw_user_meta_data jsonb);
    create function auth.uid() returns uuid language sql stable as $$ select null::uuid $$;`);
  for (const f of readdirSync(join(root, "supabase/migrations")).filter((f) => f.endsWith(".sql") && !f.includes("storage")).sort())
    await c.query(readFileSync(join(root, "supabase/migrations", f), "utf8"));

  const enums = (await c.query(`select t.typname, array_agg(e.enumlabel order by e.enumsortorder)::text[] labels from pg_type t join pg_enum e on e.enumtypid = t.oid join pg_namespace n on n.oid = t.typnamespace where n.nspname = 'public' group by t.typname order by 1`)).rows as { typname: string; labels: string[] }[];
  const cols = (await c.query(`select c.table_name, c.column_name, c.udt_name, c.is_nullable, c.column_default, c.is_identity, t.table_type from information_schema.columns c join information_schema.tables t using (table_schema, table_name) where c.table_schema = 'public' order by c.table_name, c.ordinal_position`)).rows as { table_name: string; column_name: string; udt_name: string; is_nullable: string; column_default: string | null; is_identity: string; table_type: string }[];

  const enumNames = new Set(enums.map((e) => e.typname));
  const tsType = (udt: string): string => {
    if (udt.startsWith("_")) return `${tsType(udt.slice(1))}[]`;
    if (enumNames.has(udt)) return pascal(udt);
    return scalar[udt] ?? "unknown";
  };

  const out: string[] = ["// GENERATED by scripts/gen-types.ts from supabase/migrations — do not edit.", "export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];", ""];
  for (const e of enums) out.push(`export type ${pascal(e.typname)} = ${e.labels.map((l) => JSON.stringify(l)).join(" | ")};`);
  out.push("");
  const tables = [...new Set(cols.map((r) => r.table_name))];
  for (const t of tables) {
    const rows = cols.filter((r) => r.table_name === t);
    out.push(`export type ${pascal(t)}Row = {`);
    for (const r of rows) out.push(`  ${r.column_name}: ${tsType(r.udt_name)}${r.is_nullable === "YES" ? " | null" : ""};`);
    out.push("};");
    if (rows[0]!.table_type === "BASE TABLE") {
      out.push(`export type ${pascal(t)}Insert = {`);
      for (const r of rows) {
        const optional = r.is_nullable === "YES" || r.column_default !== null || r.is_identity === "YES";
        out.push(`  ${r.column_name}${optional ? "?" : ""}: ${tsType(r.udt_name)}${r.is_nullable === "YES" ? " | null" : ""};`);
      }
      out.push("};");
    }
    out.push("");
  }
  out.push("export type Tables = {", ...tables.map((t) => `  ${t}: ${pascal(t)}Row;`), "};", "export type TableName = keyof Tables;", "");
  writeFileSync(join(root, "src/lib/backend/db-types.ts"), out.join("\n"));
  console.log(`db-types.ts: ${tables.length} tables/views, ${enums.length} enums`);
  await c.end();
}
main().catch((e) => { console.error(e); process.exitCode = 1; }).finally(async () => { await server.stop().catch(() => {}); rmSync(dir, { recursive: true, force: true }); });
