-- 0021 · Catalogue refresh: fabric groups, print-size rules, sizes to 8XL, Sports T-Shirt
--
-- Product content lives in the seed, but the live catalogue was seeded before the
-- client's fabric rules existed, so the refreshed product rows ship as a migration.
-- Generated from supabase/seed.sql (scripts/build-seed.ts). Guarded: on an empty
-- database (tests, fresh installs) the seed itself loads the catalogue afterwards.
do $cat$
begin
  if exists (select 1 from categories) then
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('custom-t-shirt', 'Cotton T-Shirt', (select id from categories where slug = 'apparel'), 'Combed cotton round-collar tee — chest logo up to 8 × 8 cm, back up to 10 × 25 cm.', 'Our most-ordered garment. A mid-weight combed cotton round-collar tee that holds its shape through wash after wash, printed with the method that suits your artwork — screen for bold spot colour, DTF for photographic detail. Cotton takes a placed print: a logo up to 8 × 8 cm on the left or right chest and a back print up to 10 × 25 cm. For an all-over design, choose the sports-fabric T-shirt.', '{"materials":["100% combed cotton, 180 gsm","Cotton/poly blend, 160 gsm"],"fabric":"cotton","sizes":["XS","S","M","L","XL","2XL","3XL","4XL","5XL","6XL","7XL","8XL"],"colours":[{"name":"White","hex":"#f5f5f2"},{"name":"Black","hex":"#17171a"},{"name":"Navy","hex":"#1b2447"},{"name":"Royal","hex":"#2a35d6"},{"name":"Sky","hex":"#4db4e8"},{"name":"Red","hex":"#d4302b"},{"name":"Forest","hex":"#1f5a3d"},{"name":"Yellow","hex":"#ffd60a"},{"name":"Orange","hex":"#f2711c"},{"name":"Heather","hex":"#9a9da3"},{"name":"Sand","hex":"#d8cbb0"},{"name":"Maroon","hex":"#6b1f2a"}],"printMethods":["screen","dtf"],"customisation":["Left or right chest logo (up to 8 × 8 cm)","Back print (up to 10 × 25 cm)","Sleeve print","Neck label","Individual names & numbers","Pantone-matched ink"],"useCases":["Events & festivals","Staff uniforms","School & university","Merchandise","Campaign giveaways"],"studio":{"garment":"tee","areas":[{"key":"left-chest","label":"Left chest","widthMm":80,"heightMm":80},{"key":"right-chest","label":"Right chest","widthMm":80,"heightMm":80},{"key":"back","label":"Back","widthMm":100,"heightMm":250},{"key":"left-sleeve","label":"Left sleeve","widthMm":90,"heightMm":90},{"key":"right-sleeve","label":"Right sleeve","widthMm":90,"heightMm":90}]},"seo":{"title":"Cotton T-Shirt Printing in Laos","description":"Design your own cotton T-shirt online — chest logo, back print and sleeves in sizes XS to 8XL — and request a quote. Screen and DTF printing in Vientiane with a 12-piece minimum."}}'::jsonb, 12, 5, 10, 'estimated', 55000, 'per piece', true, 1, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('sports-t-shirt', 'Sports T-Shirt', (select id from categories where slug = 'apparel'), 'Polyester sports tee with free-flow all-over sublimation — the whole shirt is the canvas.', 'The same cut as our cotton tee in a breathable polyester sports fabric. Sublimation dyes the fibre itself, so the design is free-flow: it can run from collar to hem and sleeve to sleeve with no rectangle to stay inside, and it never cracks, peels or fades. Every piece can carry its own name and number.', '{"materials":["Dry-fit polyester, 140 gsm","Interlock polyester, 150 gsm"],"fabric":"sports","sizes":["XS","S","M","L","XL","2XL","3XL","4XL","5XL","6XL","7XL","8XL"],"colours":[{"name":"White","hex":"#f5f5f2"},{"name":"Black","hex":"#17171a"},{"name":"Navy","hex":"#1b2447"},{"name":"Royal","hex":"#2a35d6"},{"name":"Sky","hex":"#4db4e8"},{"name":"Red","hex":"#d4302b"},{"name":"Forest","hex":"#1f5a3d"},{"name":"Yellow","hex":"#ffd60a"},{"name":"Orange","hex":"#f2711c"},{"name":"Heather","hex":"#9a9da3"},{"name":"Sand","hex":"#d8cbb0"},{"name":"Maroon","hex":"#6b1f2a"}],"printMethods":["sublimation","dtf"],"customisation":["Free-flow all-over print","Names & numbers","Sponsor panels","Matching shorts on request"],"useCases":["Sports teams","Running events","School sports days","Outdoor crews","Festival merchandise"],"studio":{"garment":"sports-tee","areas":[{"key":"front","label":"Front","widthMm":740,"heightMm":750,"freeFlow":true},{"key":"back","label":"Back","widthMm":740,"heightMm":750,"freeFlow":true}]},"seo":{"title":"Sports T-Shirt Sublimation Printing in Laos","description":"Design an all-over sublimated sports T-shirt online — free-flow artwork across the whole shirt, sizes XS to 8XL — and request a quote from SPP in Vientiane."}}'::jsonb, 12, 7, 12, 'quote', null, 'per piece', true, 2, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('polo-shirt', 'Polo Shirt', (select id from categories where slug = 'apparel'), 'Cotton piqué polo for uniforms — chest logo up to 8 × 8 cm, back up to 10 × 25 cm.', 'The corporate standard. A structured cotton piqué polo with a clean placket and a collar that stays flat, finished with embroidery or print on the left or right chest (up to 8 × 8 cm) and a back print up to 10 × 25 cm. Built for daily wear by hotel, bank, restaurant and retail teams.', '{"materials":["Cotton piqué, 220 gsm","Poly-cotton piqué, 200 gsm"],"fabric":"cotton","sizes":["XS","S","M","L","XL","2XL","3XL","4XL","5XL","6XL","7XL","8XL"],"colours":[{"name":"White","hex":"#f5f5f2"},{"name":"Black","hex":"#17171a"},{"name":"Navy","hex":"#1b2447"},{"name":"Royal","hex":"#2a35d6"},{"name":"Sky","hex":"#4db4e8"},{"name":"Red","hex":"#d4302b"},{"name":"Forest","hex":"#1f5a3d"},{"name":"Yellow","hex":"#ffd60a"},{"name":"Orange","hex":"#f2711c"},{"name":"Heather","hex":"#9a9da3"},{"name":"Sand","hex":"#d8cbb0"},{"name":"Maroon","hex":"#6b1f2a"}],"printMethods":["embroidery","screen","dtf"],"customisation":["Left or right chest embroidery or print (up to 8 × 8 cm)","Back print (up to 10 × 25 cm)","Sleeve flag or logo","Contrast collar & placket","Individual names"],"useCases":["Corporate uniforms","Hospitality","Retail teams","Schools","Golf & events"],"studio":{"garment":"polo","areas":[{"key":"left-chest","label":"Left chest","widthMm":80,"heightMm":80},{"key":"right-chest","label":"Right chest","widthMm":80,"heightMm":80},{"key":"back","label":"Back","widthMm":100,"heightMm":250},{"key":"left-sleeve","label":"Left sleeve","widthMm":90,"heightMm":90},{"key":"right-sleeve","label":"Right sleeve","widthMm":90,"heightMm":90}]},"seo":{"title":"Custom Polo Shirts & Uniforms in Laos","description":"Embroidered and printed polo shirts for corporate, hospitality and school uniforms. Preview your logo on the garment and request a bulk quote."}}'::jsonb, 12, 7, 14, 'estimated', 80000, 'per piece', true, 3, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('sleeveless-jersey', 'Sleeveless Jersey', (select id from categories where slug = 'apparel'), 'Lightweight sports singlet with free-flow all-over sublimation.', 'A breathable sleeveless jersey for football, basketball, running clubs and outdoor work. Sublimation printing dyes the fibre itself, so the design is free-flow across the whole jersey and colour never cracks, peels or fades — and every piece can carry its own name and number.', '{"materials":["Dry-fit polyester mesh, 140 gsm","Interlock polyester, 150 gsm"],"fabric":"sports","sizes":["XS","S","M","L","XL","2XL","3XL","4XL","5XL","6XL","7XL","8XL"],"colours":[{"name":"White","hex":"#f5f5f2"},{"name":"Black","hex":"#17171a"},{"name":"Navy","hex":"#1b2447"},{"name":"Royal","hex":"#2a35d6"},{"name":"Sky","hex":"#4db4e8"},{"name":"Red","hex":"#d4302b"},{"name":"Forest","hex":"#1f5a3d"},{"name":"Yellow","hex":"#ffd60a"},{"name":"Orange","hex":"#f2711c"},{"name":"Heather","hex":"#9a9da3"},{"name":"Sand","hex":"#d8cbb0"},{"name":"Maroon","hex":"#6b1f2a"}],"printMethods":["sublimation","dtf"],"customisation":["Free-flow all-over print","Names & numbers","Sponsor panels","Matching shorts on request"],"useCases":["Sports teams","Running events","Outdoor crews","School sports days"],"studio":{"garment":"sleeveless","areas":[{"key":"front","label":"Front","widthMm":480,"heightMm":770,"freeFlow":true},{"key":"back","label":"Back","widthMm":480,"heightMm":770,"freeFlow":true}]},"seo":{}}'::jsonb, 10, 7, 12, 'estimated', 45000, 'per piece', false, 4, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('uv-arm-sleeve', 'UV Arm Sleeve', (select id from categories where slug = 'apparel'), 'SPF 50+ sleeve for riders, farmers and athletes.', 'A full-arm compression sleeve in cool-touch fabric rated SPF 50+. A staple for motorbike riders and outdoor workers across Laos, and one of the most cost-effective branded items we make.', '{"materials":["Cool-touch nylon/spandex","Polyester/spandex"],"fabric":"sports","sizes":["S/M","L/XL"],"colours":[{"name":"White","hex":"#f5f5f2"},{"name":"Black","hex":"#17171a"},{"name":"Navy","hex":"#1b2447"},{"name":"Royal","hex":"#2a35d6"},{"name":"Sky","hex":"#4db4e8"},{"name":"Red","hex":"#d4302b"}],"printMethods":["sublimation","dtf"],"customisation":["Logo print","All-over pattern","Branded packaging"],"useCases":["Delivery riders","Agriculture","Sports","Promotional giveaways"],"studio":null,"seo":{}}'::jsonb, 50, 7, 12, 'estimated', 35000, 'per pair', false, 5, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('sports-cap', 'Cap', (select id from categories where slug = 'accessories'), 'Snapback, fitted or trucker — embroidered front panel.', 'Structured six-panel caps, five-panel truckers and classic snapbacks. 3D-puff or flat embroidery on the front panel, with optional side and back hits.', '{"materials":["Cotton twill","Polyester mesh back","Brushed cotton"],"fabric":"other","sizes":["Adjustable"],"colours":[{"name":"White","hex":"#f5f5f2"},{"name":"Black","hex":"#17171a"},{"name":"Navy","hex":"#1b2447"},{"name":"Royal","hex":"#2a35d6"},{"name":"Sky","hex":"#4db4e8"},{"name":"Red","hex":"#d4302b"},{"name":"Forest","hex":"#1f5a3d"},{"name":"Yellow","hex":"#ffd60a"}],"printMethods":["embroidery","dtf"],"customisation":["Front embroidery","Side & back embroidery","Woven label","Custom strap"],"useCases":["Uniforms","Merchandise","Events","Outdoor crews"],"studio":{"garment":"cap","areas":[{"key":"panel","label":"Front panel","widthMm":110,"heightMm":55}]},"seo":{}}'::jsonb, 12, 7, 14, 'estimated', 40000, 'per piece', true, 6, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('tote-bag', 'Tote Bag', (select id from categories where slug = 'accessories'), 'Canvas tote printed across the full face, with handles in your colour.', 'A reusable tote is a walking billboard with a long life. The print covers the whole face of the bag, not a small square, and the handles come in a colour you choose. Heavy natural canvas for retail, or economical non-woven for high-volume giveaways.', '{"materials":["Natural cotton canvas, 280 gsm","Non-woven polypropylene, 80 gsm"],"fabric":"canvas","sizes":["38 × 42 cm","35 × 40 cm with gusset"],"colours":[{"name":"Natural","hex":"#e6dcc5"},{"name":"Black","hex":"#17171a"},{"name":"Navy","hex":"#1b2447"},{"name":"Red","hex":"#d4302b"}],"printMethods":["screen","dtf"],"customisation":["Full-face print, one or two sides","Handle colour of your choice","Long or short handles","Inner pocket"],"useCases":["Retail","Conferences","Eco campaigns","Gift sets"],"studio":{"garment":"tote","areas":[{"key":"front","label":"Front","widthMm":350,"heightMm":360},{"key":"back","label":"Back","widthMm":350,"heightMm":360}]},"seo":{}}'::jsonb, 50, 7, 12, 'estimated', 25000, 'per piece', true, 7, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('umbrella', 'Branded Umbrella', (select id from categories where slug = 'accessories'), 'Golf, folding and café parasols with panel printing.', 'From hand-held golf umbrellas to two-metre café parasols. Logos are printed per panel, so a single umbrella can carry your mark on every side.', '{"materials":["Pongee polyester canopy","Fibreglass ribs","Steel or aluminium shaft"],"fabric":"other","sizes":["21\" folding","27\" golf","30\" golf","2 m parasol"],"colours":[{"name":"White","hex":"#f5f5f2"},{"name":"Black","hex":"#17171a"},{"name":"Navy","hex":"#1b2447"},{"name":"Royal","hex":"#2a35d6"},{"name":"Sky","hex":"#4db4e8"},{"name":"Red","hex":"#d4302b"},{"name":"Forest","hex":"#1f5a3d"},{"name":"Yellow","hex":"#ffd60a"}],"printMethods":["screen","sublimation"],"customisation":["1–8 panel print","Inner canopy print","Branded sleeve"],"useCases":["Hotels & resorts","Banks","Cafés & restaurants","Rainy-season promotions"],"studio":null,"seo":{}}'::jsonb, 50, 14, 25, 'quote', null, 'per piece', false, 8, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('cup-print', 'Cup Screen Printing', (select id from categories where slug = 'promotional'), 'Branded cups and sleeves for cafés and events.', 'Screen-printed paper and PET cups, cup sleeves and lids. The highest-frequency brand touchpoint a café owns — every drink becomes an advertisement that leaves the shop.', '{"materials":["PET cold cups","Double-wall paper cups","Kraft sleeves"],"fabric":"other","sizes":["8 oz","12 oz","16 oz","22 oz"],"colours":[],"printMethods":["screen","offset"],"customisation":["1–4 colour print","Full-wrap artwork","Seasonal editions"],"useCases":["Cafés","Bubble tea","Restaurants","Festivals"],"studio":null,"seo":{}}'::jsonb, 1000, 10, 18, 'quote', null, 'per 1,000', false, 9, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('custom-pillow', 'Photo-Print Pillow', (select id from categories where slug = 'promotional'), 'Full-colour printed cushions for retail and gifting.', 'Soft-touch cushions printed edge to edge in full colour. Popular for hotel gifting, retail lines and mascots.', '{"materials":["Velvet-touch polyester cover","PP cotton fill"],"fabric":"other","sizes":["35 × 35 cm","45 × 45 cm","Custom shape"],"colours":[],"printMethods":["sublimation"],"customisation":["Double-sided print","Custom shape cut","Zip cover"],"useCases":["Gifts","Hotels","Retail","Mascots"],"studio":null,"seo":{}}'::jsonb, 20, 7, 12, 'estimated', 50000, 'per piece', false, 10, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('fleece-blanket', 'Printed Fleece Blanket', (select id from categories where slug = 'promotional'), 'Soft fleece with full-bleed custom printing.', 'A premium cool-season gift. Full-bleed sublimation on soft fleece, folded and ribboned or boxed with your branding.', '{"materials":["Polar fleece","Flannel fleece"],"fabric":"other","sizes":["100 × 150 cm","150 × 200 cm"],"colours":[],"printMethods":["sublimation"],"customisation":["Full-bleed print","Embroidered corner","Gift packaging"],"useCases":["Corporate gifts","Hotels","Wholesale"],"studio":null,"seo":{}}'::jsonb, 20, 10, 15, 'estimated', 120000, 'per piece', false, 11, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('fabric-face-mask', 'Fabric Face Mask', (select id from categories where slug = 'promotional'), 'Washable printed masks for teams and giveaways.', 'Two and three-layer washable masks with logo or all-over print. Low cost, high visibility.', '{"materials":["Cotton outer","Polyester outer with cotton lining"],"fabric":"other","sizes":["Adult","Child"],"colours":[{"name":"White","hex":"#f5f5f2"},{"name":"Black","hex":"#17171a"},{"name":"Navy","hex":"#1b2447"},{"name":"Royal","hex":"#2a35d6"},{"name":"Sky","hex":"#4db4e8"},{"name":"Red","hex":"#d4302b"}],"printMethods":["sublimation","dtf"],"customisation":["Logo print","All-over pattern","Individual packaging"],"useCases":["Corporate","Clinics","Dust-season campaigns"],"studio":null,"seo":{}}'::jsonb, 100, 5, 10, 'estimated', 8000, 'per piece', false, 12, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('poster', 'Posters & Flyers', (select id from categories where slug = 'print'), 'Offset and digital print from A5 to A0.', 'Short-run digital for next-day needs, offset for volume. Colour-managed on coated, uncoated and synthetic stocks.', '{"materials":["Art paper 128–300 gsm","Uncoated offset","Synthetic waterproof"],"fabric":"other","sizes":["A5","A4","A3","A2","A1","A0"],"colours":[],"printMethods":["offset","large-format"],"customisation":["Matt / gloss lamination","Spot UV","Folding & creasing"],"useCases":["Promotions","Menus","Events","Retail point-of-sale"],"studio":null,"seo":{}}'::jsonb, 50, 2, 7, 'quote', null, 'per run', false, 13, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('a-board', 'A-Board', (select id from categories where slug = 'display'), 'Double-sided pavement sign with swappable prints.', 'A weighted, double-sided pavement sign. Prints slide out, so one frame serves every promotion you run this year.', '{"materials":["Powder-coated steel frame","Aluminium snap frame","PVC print panels"],"fabric":"other","sizes":["A1","A0","60 × 90 cm"],"colours":[],"printMethods":["large-format","uv"],"customisation":["Swappable inserts","Header panel","Water-fill base"],"useCases":["Cafés","Retail","Events","Way-finding"],"studio":null,"seo":{}}'::jsonb, 1, 5, 10, 'quote', null, 'per unit', false, 14, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('j-flag', 'J-Flag', (select id from categories where slug = 'display'), 'Feather flags that catch wind and attention.', 'Tall, curved feather flags on a flexible pole. Visible from the far end of the street and packed into a bag small enough for a motorbike.', '{"materials":["Knitted polyester flag","Fibreglass pole","Cross base, spike or water base"],"fabric":"other","sizes":["2.5 m","3.5 m","4.5 m"],"colours":[],"printMethods":["sublimation"],"customisation":["Single or double-sided","Base type","Carry bag"],"useCases":["Showrooms","Events","Openings","Roadside promotion"],"studio":null,"seo":{}}'::jsonb, 2, 5, 10, 'quote', null, 'per set', false, 15, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('promo-counter', 'Kiosk & Promotion Counter', (select id from categories where slug = 'display'), 'Portable sampling counters and branded kiosks.', 'Fold-flat promotion counters for sampling teams, through to fabricated kiosks for malls and events. Designed around how your staff actually stand, store and serve.', '{"materials":["PP / ABS portable counter","Aluminium frame","Custom MDF & acrylic fabrication"],"fabric":"other","sizes":["Portable 80 × 40 × 200 cm","Custom build"],"colours":[],"printMethods":["large-format","uv","vinyl-cut"],"customisation":["Header board","Shelving","Lighting","Full custom fabrication"],"useCases":["Product sampling","Mall activations","Trade fairs","Bank & telco sign-ups"],"studio":null,"seo":{}}'::jsonb, 1, 7, 21, 'quote', null, 'per unit', false, 16, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('vinyl-banner', 'Vinyl Banner & Roll-Up', (select id from categories where slug = 'signage'), 'Large-format banners, roll-up stands and wall graphics.', 'Outdoor-grade vinyl with welded hems and eyelets, retractable roll-up stands, and adhesive wall graphics — printed at large-format resolution with UV-stable inks.', '{"materials":["Frontlit PVC 440 gsm","Blockout PVC","Mesh PVC","Adhesive vinyl"],"fabric":"other","sizes":["Roll-up 80 × 200 cm","Custom to 5 m wide"],"colours":[],"printMethods":["large-format"],"customisation":["Hems & eyelets","Pole pockets","Roll-up cassette"],"useCases":["Shops","Events","Construction hoardings","Exhibitions"],"studio":null,"seo":{}}'::jsonb, 1, 2, 5, 'estimated', 80000, 'per m²', false, 17, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('led-signage', 'LED & Shopfront Signage', (select id from categories where slug = 'signage'), 'Illuminated letters, lightboxes and fascia signs.', 'Channel letters, lightboxes and full fascia builds — surveyed, designed, fabricated and installed by one team. High-brightness LEDs with low running cost and long service life.', '{"materials":["Acrylic faces","Aluminium composite","Stainless returns","High-efficiency LED modules"],"fabric":"other","sizes":["Made to measure"],"colours":[],"printMethods":["uv","vinyl-cut"],"customisation":["Front-lit, halo or edge-lit","Site survey","Installation & maintenance"],"useCases":["Shopfronts","Offices","Restaurants","Hotels"],"studio":null,"seo":{}}'::jsonb, 1, 10, 25, 'quote', null, 'per project', true, 18, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('billboard-rental', 'Billboard Rental', (select id from categories where slug = 'outdoor'), 'Bookable billboard sites across the provinces of Laos.', 'Choose a site on the SPP Outdoor Network map, preview your artwork on the structure, and request the dates you need. We print, install, maintain and report.', '{"materials":["Frontlit & backlit flex","Steel monopole and rooftop structures"],"fabric":"other","sizes":["6 × 3 m","8 × 4 m","10 × 5 m","12 × 6 m","14 × 7 m"],"colours":[],"printMethods":["large-format"],"customisation":["Artwork design","Print & installation","QR campaign tracking","Multi-site packages"],"useCases":["Brand launches","Telecom & banking","Tourism","Government & NGO campaigns"],"studio":null,"seo":{"title":"Billboard Rental & Outdoor Advertising in Laos","description":"Explore available billboard locations in Vientiane and across Laos on an interactive map. Preview your artwork and request a booking."}}'::jsonb, 1, 7, 14, 'estimated', null, 'per month', true, 19, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into products(slug, name, category_id, summary, description, data, moq, lead_min_days, lead_max_days, pricing_mode, price_from_lak, price_unit, featured, sort, status)
     values ('vehicle-wrap', 'Vehicle Branding', (select id from categories where slug = 'vehicle'), 'Full wraps, partial wraps and fleet decals.', 'Cast vinyl wraps for cars, vans, trucks and tuk-tuks. We template the vehicle, design to its panels, print, laminate and install.', '{"materials":["Cast wrap vinyl","UV over-laminate","Reflective & perforated window film"],"fabric":"other","sizes":["Motorbike box","Car","Pickup","Van","Truck"],"colours":[],"printMethods":["large-format","vinyl-cut"],"customisation":["Full or partial wrap","Fleet roll-out","Removal & re-wrap"],"useCases":["Delivery fleets","Service vehicles","Food trucks","Campaign vehicles"],"studio":null,"seo":{}}'::jsonb, 1, 5, 12, 'quote', null, 'per vehicle', false, 20, 'published')
     on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, data = excluded.data, moq = excluded.moq, sort = excluded.sort;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'custom-t-shirt' and b.slug = 'sports-t-shirt' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'custom-t-shirt' and b.slug = 'polo-shirt' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 2 from products a, products b where a.slug = 'custom-t-shirt' and b.slug = 'tote-bag' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'sports-t-shirt' and b.slug = 'sleeveless-jersey' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'sports-t-shirt' and b.slug = 'custom-t-shirt' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 2 from products a, products b where a.slug = 'sports-t-shirt' and b.slug = 'sports-cap' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'polo-shirt' and b.slug = 'custom-t-shirt' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'polo-shirt' and b.slug = 'sports-cap' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 2 from products a, products b where a.slug = 'polo-shirt' and b.slug = 'fabric-face-mask' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'sleeveless-jersey' and b.slug = 'sports-t-shirt' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'sleeveless-jersey' and b.slug = 'uv-arm-sleeve' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 2 from products a, products b where a.slug = 'sleeveless-jersey' and b.slug = 'sports-cap' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'uv-arm-sleeve' and b.slug = 'sleeveless-jersey' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'uv-arm-sleeve' and b.slug = 'sports-cap' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'sports-cap' and b.slug = 'custom-t-shirt' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'sports-cap' and b.slug = 'polo-shirt' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'tote-bag' and b.slug = 'custom-t-shirt' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'tote-bag' and b.slug = 'umbrella' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'umbrella' and b.slug = 'tote-bag' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'umbrella' and b.slug = 'cup-print' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'cup-print' and b.slug = 'tote-bag' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'cup-print' and b.slug = 'poster' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'custom-pillow' and b.slug = 'fleece-blanket' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'fleece-blanket' and b.slug = 'custom-pillow' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'fabric-face-mask' and b.slug = 'polo-shirt' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'poster' and b.slug = 'a-board' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'poster' and b.slug = 'vinyl-banner' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'a-board' and b.slug = 'j-flag' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'a-board' and b.slug = 'poster' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'j-flag' and b.slug = 'a-board' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'j-flag' and b.slug = 'promo-counter' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'promo-counter' and b.slug = 'j-flag' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'promo-counter' and b.slug = 'a-board' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'vinyl-banner' and b.slug = 'a-board' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'vinyl-banner' and b.slug = 'led-signage' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'led-signage' and b.slug = 'vinyl-banner' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'led-signage' and b.slug = 'billboard-rental' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'billboard-rental' and b.slug = 'led-signage' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'billboard-rental' and b.slug = 'vehicle-wrap' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 0 from products a, products b where a.slug = 'vehicle-wrap' and b.slug = 'billboard-rental' on conflict do nothing;
    insert into product_relations(product_id, related_id, sort) select a.id, b.id, 1 from products a, products b where a.slug = 'vehicle-wrap' and b.slug = 'led-signage' on conflict do nothing;
    -- keep the facts that the upsert does not touch in step with the seed
    update products set pricing_mode = 'quote', price_from_lak = null where slug = 'sports-t-shirt';
  end if;
end
$cat$;
