-- 0028 · More room to design: print areas for shirts and caps
--
-- Cotton T-shirt and polo gain a full front and full back (up to 30 × 40 cm), an
-- upper-back strip (25 × 10 cm) and larger sleeves (10 × 10 cm) beside the 8 × 8 cm
-- chest logos. The sports T-shirt gains free-flow sleeves. The cap gains both side
-- panels and the back. Replaces the earlier cotton back cap of 10 × 25 cm.
--
-- Only the Studio set-up is replaced outright. Wording (summary, description,
-- customisation list, SEO description) changes ONLY where it still reads exactly as
-- seeded, so anything staff have rewritten in the Command Center is left alone.
-- Generated from src/content/seed/catalogue.ts. Guarded: on an empty database the
-- seed loads the catalogue afterwards.
do $cat$
begin
  if exists (select 1 from products) then
    -- Cotton T-Shirt
    update products set data = jsonb_set(data, '{studio}', '{"garment":"tee","areas":[{"key":"front","label":"Full front","widthMm":300,"heightMm":400},{"key":"left-chest","label":"Left chest","widthMm":80,"heightMm":80},{"key":"right-chest","label":"Right chest","widthMm":80,"heightMm":80},{"key":"back","label":"Full back","widthMm":300,"heightMm":400},{"key":"upper-back","label":"Upper back","widthMm":250,"heightMm":100},{"key":"left-sleeve","label":"Left sleeve","widthMm":100,"heightMm":100},{"key":"right-sleeve","label":"Right sleeve","widthMm":100,"heightMm":100}]}'::jsonb) where slug = 'custom-t-shirt';
    update products set data = jsonb_set(data, '{customisation}', '["Full front print (up to 30 × 40 cm)","Full back print (up to 30 × 40 cm)","Left or right chest logo (up to 8 × 8 cm)","Upper back strip (up to 25 × 10 cm)","Sleeve prints (up to 10 × 10 cm)","Neck label","Individual names & numbers","Pantone-matched ink"]'::jsonb) where slug = 'custom-t-shirt' and data->'customisation' = '["Left or right chest logo (up to 8 × 8 cm)","Back print (up to 10 × 25 cm)","Sleeve print","Neck label","Individual names & numbers","Pantone-matched ink"]'::jsonb;
    update products set data = jsonb_set(data, '{seo,description}', to_jsonb('Design your own cotton T-shirt online — full front, chest logo, back and sleeves in sizes XS to 8XL — and request a quote. Screen and DTF printing in Vientiane with a 12-piece minimum.'::text)) where slug = 'custom-t-shirt' and data->'seo'->>'description' = 'Design your own cotton T-shirt online — chest logo, back print and sleeves in sizes XS to 8XL — and request a quote. Screen and DTF printing in Vientiane with a 12-piece minimum.';
    update products set summary = 'Combed cotton round-collar tee — full front and back prints, chest logo, upper back and both sleeves.' where slug = 'custom-t-shirt' and summary = 'Combed cotton round-collar tee — chest logo up to 8 × 8 cm, back up to 10 × 25 cm.';
    update products set description = 'Our most-ordered garment. A mid-weight combed cotton round-collar tee that holds its shape through wash after wash, printed with the method that suits your artwork — screen for bold spot colour, DTF for photographic detail. Cotton takes placed prints: a full front or back up to 30 × 40 cm, a logo up to 8 × 8 cm on the left or right chest, a strip across the upper back and a print on each sleeve. For an all-over design, choose the sports-fabric T-shirt.' where slug = 'custom-t-shirt' and description = 'Our most-ordered garment. A mid-weight combed cotton round-collar tee that holds its shape through wash after wash, printed with the method that suits your artwork — screen for bold spot colour, DTF for photographic detail. Cotton takes a placed print: a logo up to 8 × 8 cm on the left or right chest and a back print up to 10 × 25 cm. For an all-over design, choose the sports-fabric T-shirt.';
    -- Polo Shirt
    update products set data = jsonb_set(data, '{studio}', '{"garment":"polo","areas":[{"key":"left-chest","label":"Left chest","widthMm":80,"heightMm":80},{"key":"right-chest","label":"Right chest","widthMm":80,"heightMm":80},{"key":"front","label":"Front panel","widthMm":270,"heightMm":300},{"key":"back","label":"Full back","widthMm":300,"heightMm":400},{"key":"upper-back","label":"Upper back","widthMm":250,"heightMm":100},{"key":"left-sleeve","label":"Left sleeve","widthMm":100,"heightMm":100},{"key":"right-sleeve","label":"Right sleeve","widthMm":100,"heightMm":100}]}'::jsonb) where slug = 'polo-shirt';
    update products set data = jsonb_set(data, '{customisation}', '["Left or right chest embroidery or print (up to 8 × 8 cm)","Front panel below the placket (up to 27 × 30 cm)","Full back print (up to 30 × 40 cm)","Upper back strip (up to 25 × 10 cm)","Sleeve flag or logo (up to 10 × 10 cm)","Contrast collar & placket","Individual names"]'::jsonb) where slug = 'polo-shirt' and data->'customisation' = '["Left or right chest embroidery or print (up to 8 × 8 cm)","Back print (up to 10 × 25 cm)","Sleeve flag or logo","Contrast collar & placket","Individual names"]'::jsonb;
    update products set summary = 'Cotton piqué polo for uniforms — chest logo, front panel, full back, upper back and both sleeves.' where slug = 'polo-shirt' and summary = 'Cotton piqué polo for uniforms — chest logo up to 8 × 8 cm, back up to 10 × 25 cm.';
    update products set description = 'The corporate standard. A structured cotton piqué polo with a clean placket and a collar that stays flat, finished with embroidery or print on the left or right chest (up to 8 × 8 cm), a full back print up to 30 × 40 cm, the upper back and both sleeves. Built for daily wear by hotel, bank, restaurant and retail teams.' where slug = 'polo-shirt' and description = 'The corporate standard. A structured cotton piqué polo with a clean placket and a collar that stays flat, finished with embroidery or print on the left or right chest (up to 8 × 8 cm) and a back print up to 10 × 25 cm. Built for daily wear by hotel, bank, restaurant and retail teams.';
    -- Sports T-Shirt
    update products set data = jsonb_set(data, '{studio}', '{"garment":"sports-tee","areas":[{"key":"front","label":"Front","widthMm":740,"heightMm":750,"freeFlow":true},{"key":"back","label":"Back","widthMm":740,"heightMm":750,"freeFlow":true},{"key":"left-sleeve","label":"Left sleeve","widthMm":230,"heightMm":260,"freeFlow":true},{"key":"right-sleeve","label":"Right sleeve","widthMm":230,"heightMm":260,"freeFlow":true}]}'::jsonb) where slug = 'sports-t-shirt';
    -- Cap
    update products set data = jsonb_set(data, '{studio}', '{"garment":"cap","areas":[{"key":"panel","label":"Front panel","widthMm":110,"heightMm":55},{"key":"left-side","label":"Left side","widthMm":60,"heightMm":40},{"key":"right-side","label":"Right side","widthMm":60,"heightMm":40},{"key":"back","label":"Back","widthMm":70,"heightMm":30}]}'::jsonb) where slug = 'sports-cap';
  end if;
end
$cat$;
